package transformerts

import (
	"fmt"
	"strings"
)

// generateClientStructure generates the new Prisma-like client structure
func (t *TypeScriptTransformer) generateClientStructure() {
	// Always emit types declaration content from Types + Functions (valid .d.ts).
	t.Output.GenerateTypesFile()

	if t.Output.PackageName == "" {
		return
	}

	// Generate per-package client code
	t.generatePackageClient()

	// Generate main client
	t.generateMainClient()
}

// generatePackageClient generates the per-package client code
func (t *TypeScriptTransformer) generatePackageClient() {
	var lines []string

	lines = append(lines, `// Auto-generated client for `+t.Output.PackageName+` package
// Generated by Forst TypeScript Transformer

import { ForstSidecarClient as SidecarClient } from '@forst/sidecar';
`)

	// Add type definitions directly in the client file
	if len(t.Output.Types) > 0 {
		lines = append(lines, "// Type definitions")
		for _, tsType := range t.Output.Types {
			lines = append(lines, tsType)
		}
		lines = append(lines, "")
	}

	// Generate package namespace
	lines = append(lines, fmt.Sprintf(`export const %s = (client: SidecarClient) => ({`, t.Output.PackageName))

	// Add function implementations
	for _, function := range t.Output.Functions {
		funcName := function.Name

		// Build parameter list from structured data
		paramsSig := make([]string, len(function.Parameters))
		paramNames := make([]string, len(function.Parameters))

		for i, param := range function.Parameters {
			paramsSig[i] = fmt.Sprintf("%s: %s", param.Name, param.Type)
			paramNames[i] = param.Name
		}

		paramsSigStr := strings.Join(paramsSig, ", ")
		paramNamesStr := strings.Join(paramNames, ", ")

		// Generate implementation
		impl := fmt.Sprintf(`  %s: async (%s): Promise<%s> => {`, funcName, paramsSigStr, function.ReturnType)

		// Create args object for single parameter, or use spread for multiple
		if len(paramNames) == 1 {
			impl += fmt.Sprintf(`
    const response = await client.invokeFunction<%s>('%s', '%s', %s);`,
				function.ReturnType, t.Output.PackageName, funcName, paramNames[0])
		} else if len(paramNames) > 1 {
			impl += fmt.Sprintf(`
    const response = await client.invokeFunction<%s>('%s', '%s', { %s });`,
				function.ReturnType, t.Output.PackageName, funcName, paramNamesStr)
		} else {
			impl += fmt.Sprintf(`
    const response = await client.invokeFunction<%s>('%s', '%s', {});`,
				function.ReturnType, t.Output.PackageName, funcName)
		}

		impl += fmt.Sprintf(`
    if (!response.success) {
      throw new Error(response.error || '%s.%s failed');
    }
    return response.result;
  },`, t.Output.PackageName, funcName)

		lines = append(lines, impl)
	}

	lines = append(lines, `});

`)

	t.Output.ClientCode = lines
}

// generateMainClient generates the main client class
func (t *TypeScriptTransformer) generateMainClient() {
	mainClient := `// Auto-generated Forst Client
// Generated by Forst TypeScript Transformer

import { ForstSidecarClient as SidecarClient } from '@forst/sidecar';
import { ` + t.Output.PackageName + ` } from './` + t.Output.PackageName + `.client';
import * as types from './types';

export interface ForstClientConfig {
  baseUrl?: string;
  timeout?: number;
  retries?: number;
}

export class ForstClient {
  private client: SidecarClient;
  public ` + t.Output.PackageName + `: ReturnType<typeof ` + t.Output.PackageName + `>;

  constructor(config?: ForstClientConfig) {
    const defaultConfig = {
      baseUrl: process.env.FORST_BASE_URL || 'http://localhost:8080',
      timeout: 30000,
      retries: 3,
      ...config,
    };

    this.client = new SidecarClient(defaultConfig);
    this.` + t.Output.PackageName + ` = ` + t.Output.PackageName + `(this.client);
  }
}

// Export types
export * from './types';

// Export default
export default ForstClient;`

	t.Output.MainClient = mainClient
}
