package transformerts

import (
	"fmt"
	"strings"
)

// Relative imports from src/core/ and src/pkg/ up to compiler-owned modules in src/.
const (
	coreTransportModuleSpecifier = "../transport/runtime.js"
	coreTypesModuleSpecifier     = "../types.js"
)

// tsClientExportName is the JavaScript identifier for export const … and import { … }.
// It follows SourceFileStem when set (matches *.ft basename / generated file name); otherwise PackageName.
func (t *TypeScriptTransformer) tsClientExportName() string {
	if t.Output.SourceFileStem != "" {
		return t.Output.SourceFileStem
	}
	return t.Output.PackageName
}

// generateClientStructure generates the new Prisma-like client structure
func (t *TypeScriptTransformer) generateClientStructure() {
	// Always emit types declaration content from Types (valid .d.ts shapes).
	t.Output.GenerateTypesFile()

	if t.Output.PackageName == "" {
		return
	}

	// Generate per-package core module (Promise implementation)
	t.generatePackageClient()

	// Generate main client factory snippet (root index is assembled in cmd/forst)
	t.generateMainClient()
}

// generatePackageClient generates the per-package core module under src/core/<pkg>.ts.
func (t *TypeScriptTransformer) generatePackageClient() {
	var lines []string

	header := strings.TrimSuffix(GeneratedHeaderComment(""), "\n")
	lines = append(lines, fmt.Sprintf(`// Auto-generated client for %s package
// Generated by Forst TypeScript Transformer
%s

import type { ForstInvokeClient } from '%s';
import { getDefaultInvokeClient } from '%s';
`, t.Output.PackageName, header, coreTransportModuleSpecifier, coreTransportModuleSpecifier))

	// Types live only in ../types.d.ts; pull exported names in for parameter/return annotations.
	exportNames := sortDedupeStrings(t.Output.ExportedTypeNames)
	if len(exportNames) > 0 {
		lines = append(lines, fmt.Sprintf("import type { %s } from '%s';", strings.Join(exportNames, ", "), coreTypesModuleSpecifier))
		lines = append(lines, "")
	}

	// Generate package namespace
	lines = append(lines, fmt.Sprintf(`export const %s = (client: ForstInvokeClient) => ({`, t.tsClientExportName()))

	// Add function implementations
	for _, function := range t.Output.Functions {
		funcName := function.Name

		// Build parameter list from structured data
		paramsSig := make([]string, len(function.Parameters))
		paramNames := make([]string, len(function.Parameters))

		for i, param := range function.Parameters {
			paramsSig[i] = fmt.Sprintf("%s: %s", param.Name, param.Type)
			paramNames[i] = param.Name
		}

		paramsSigStr := strings.Join(paramsSig, ", ")
		paramNamesStr := strings.Join(paramNames, ", ")

		// Generate implementation
		impl := fmt.Sprintf(`  %s: async (%s): Promise<%s> => {`, funcName, paramsSigStr, function.ReturnType)

		// Executor stdin expects a JSON array of positional args (see go_module_manager buildParameterExtraction).
		if len(paramNames) == 1 {
			impl += fmt.Sprintf(`
    const response = await client.invokeFunction<%s>('%s', '%s', [%s]);`,
				function.ReturnType, t.Output.PackageName, funcName, paramNames[0])
		} else if len(paramNames) > 1 {
			impl += fmt.Sprintf(`
    const response = await client.invokeFunction<%s>('%s', '%s', [%s]);`,
				function.ReturnType, t.Output.PackageName, funcName, paramNamesStr)
		} else {
			impl += fmt.Sprintf(`
    const response = await client.invokeFunction<%s>('%s', '%s', []);`,
				function.ReturnType, t.Output.PackageName, funcName)
		}

		impl += `
    return response.result;
  },`

		lines = append(lines, impl)

		if function.StreamingRowType != "" {
			var argList string
			if len(paramNames) == 1 {
				argList = paramNames[0]
			} else if len(paramNames) > 1 {
				argList = paramNamesStr
			}
			// Delegate directly to invokeStream<T>: one async generator, no wrapper re-yield
			// (for await / spread / Stream APIs compose naturally; same package/name/args as invokeFunction).
			stream := fmt.Sprintf(`  %sStream: (%s) =>
    client.invokeStream<%s>('%s', '%s', [%s]),
`,
				funcName, paramsSigStr, function.StreamingRowType,
				t.Output.PackageName, funcName, argList)
			lines = append(lines, stream)
		}
	}

	lines = append(lines, `});

`)

	// Direct named exports are SSR-safe: lazy client init, individually tree-shakeable.
	for _, line := range DirectInvokeExportLines(t.Output.PackageName, t.Output.Functions) {
		lines = append(lines, line)
		lines = append(lines, "")
	}

	t.Output.ClientCode = lines
}

// generateMainClient generates the createForstClient factory snippet for this package.
func (t *TypeScriptTransformer) generateMainClient() {
	exportName := t.tsClientExportName()
	mainClient := `// Auto-generated Forst Client
// Generated by Forst TypeScript Transformer

import { createInvokeClient } from '` + TransportModuleSpecifier + `';
import { ` + exportName + ` } from './pkg/` + exportName + `.js';

export interface ForstClientConfig {
  baseUrl?: string;
  timeout?: number;
  retries?: number;
}

export function createForstClient(config?: ForstClientConfig) {
  const client = createInvokeClient(config);
  return {
    ` + exportName + `: ` + exportName + `(client),
  };
}

export type ForstClient = ReturnType<typeof createForstClient>;

export type * from './types.js';
`

	t.Output.MainClient = mainClient
}
