package transformerts

import (
	"fmt"
	"strings"
)

// EffectPeerDependencyRange is the peerDependency floor for generate.effect.
// Layer.mock landed in Effect 3.17.
const EffectPeerDependencyRange = ">=3.17.0"

// EffectModuleStem is the compiler-owned dist file holding ForstTransport.
// Kept out of transport.js so Promise mode transport stays free of an effect import
// Effect and Promise modes share core invoke logic; error modules differ by runtime.
const EffectModuleStem = "effect"

// EmitEffectSupportESM returns dist/effect.js (ForstTransport + withTransport + ForstTransportLayer).
// Written only when generate.effect is true.
func EmitEffectSupportESM(npmPackageName string) string {
	tagPrefix := effectTagPrefix(npmPackageName)
	var b strings.Builder
	b.WriteString(`// Auto-generated Effect transport support.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

import { Effect, Layer } from "effect";
import { createInvokeClient } from "./transport.js";

/** Compose call options with an injected transport and interruption signal. */
export const withTransport = (client, options, signal) => {
  const { retries: _retries, ...rest } = options ?? {};
  return {
    ...rest,
    transport: client,
    signal: rest.signal ? AbortSignal.any([rest.signal, signal]) : signal,
  };
};

export class ForstTransport extends Effect.Service()(` + fmt.Sprintf("%q", tagPrefix+"/Transport") + `, {
  effect: Effect.sync(() => ({
    client: createInvokeClient(),
  })),
}) {}

/** Build a configured ForstTransport layer (one instance shared across packages). */
export const ForstTransportLayer = (config) =>
  Layer.effect(
    ForstTransport,
    Effect.sync(() => ({
      client: createInvokeClient(config),
    }))
  );
`)
	return b.String()
}

// EmitEffectSupportDTS returns dist/effect.d.ts.
// Ambient form uses Context.Tag so TypeScript does not parse type arguments inside a
// Service() value argument (TS1005). Runtime JS still uses Effect.Service.
func EmitEffectSupportDTS(npmPackageName string) string {
	tagPrefix := effectTagPrefix(npmPackageName)
	tag := tagPrefix + "/Transport"
	return `// Auto-generated Effect transport support.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

import { Context, Layer } from "effect";
import type { ForstInvokeClient, ForstInvokeClientConfig } from "./transport.js";

export declare const withTransport: (
  client: ForstInvokeClient,
  options: import("./transport.js").InvokeCallOptions | undefined,
  signal: AbortSignal
) => import("./transport.js").InvokeCallOptions;

export declare class ForstTransport extends Context.Tag(` + fmt.Sprintf("%q", tag) + `)<
  ForstTransport,
  { readonly client: ForstInvokeClient }
>() {
  static readonly Default: Layer.Layer<ForstTransport>;
}

export declare const ForstTransportLayer: (
  config?: ForstInvokeClientConfig
) => Layer.Layer<ForstTransport>;
`
}

func effectTagPrefix(npmPackageName string) string {
	if npmPackageName == "" {
		return "@forst/gen"
	}
	return npmPackageName
}

// EmitPackageEffectESM returns dist/pkg/<pkg>.js for Effect mode.
func EmitPackageEffectESM(m ModuleEmit, npmPackageName string) string {
	pkg := m.PackageName
	className := ServiceClassName(pkg)
	tag := effectTagPrefix(npmPackageName) + "/" + className
	var b strings.Builder
	b.WriteString("// Auto-generated public module for " + pkg + " package\n")
	b.WriteString("// Generated by Forst TypeScript Transformer\n")
	b.WriteString("// Effect mode: wraps identical core Promise implementation.\n\n")
	b.WriteString(`import { Effect } from "effect";` + "\n")
	b.WriteString(`import { ForstTransport, withTransport } from "../effect.js";` + "\n")
	b.WriteString(fmt.Sprintf("import * as core from \"../core/%s.js\";\n\n", pkg))

	// Namespace factory for createForstClient (Promise escape hatch).
	b.WriteString(fmt.Sprintf("export { %s } from \"../core/%s.js\";\n\n", pkg, pkg))

	b.WriteString(fmt.Sprintf("export class %s extends Effect.Service()(%q, {\n", className, tag))
	b.WriteString("  effect: Effect.gen(function* () {\n")
	b.WriteString("    const { client } = yield* ForstTransport;\n")
	b.WriteString("    return {\n")
	for _, fn := range m.Functions {
		params := emitParamListJS(fn.Parameters, true)
		coreArgs := emitParamListJS(fn.Parameters, false)
		if coreArgs != "" {
			coreArgs += ", "
		}
		b.WriteString(fmt.Sprintf("      %s: (%s) =>\n", fn.Name, params))
		b.WriteString("        Effect.tryPromise({\n")
		b.WriteString(fmt.Sprintf(
			"          try: (signal) => core.%s(%swithTransport(client, options, signal)),\n",
			fn.Name, coreArgs,
		))
		b.WriteString("          catch: (error) => error,\n")
		b.WriteString("        }),\n")
	}
	b.WriteString("    };\n")
	b.WriteString("  }),\n")
	b.WriteString("  dependencies: [ForstTransport.Default],\n")
	b.WriteString("  accessors: true,\n")
	b.WriteString("}) {}\n\n")

	if len(m.Functions) > 0 {
		names := make([]string, 0, len(m.Functions))
		for _, fn := range m.Functions {
			names = append(names, fn.Name)
		}
		b.WriteString(fmt.Sprintf("export const { %s } = %s;\n\n", strings.Join(names, ", "), className))
	}

	for _, fn := range m.Functions {
		if fn.StreamingRowType == "" {
			continue
		}
		b.WriteString(fmt.Sprintf("export { %sStream } from \"../core/%s.js\";\n", fn.Name, pkg))
	}

	appendOmitStubs(&b, m.Omitted)
	return b.String()
}

func effectFailureType(fn FunctionSignature) string {
	if fn.FailureType != "" {
		return fn.FailureType
	}
	return "InvokeFailure"
}

// functionFailureTypeAlias returns a per-function exported alias name when the
// failure union is compound, otherwise the compact failure type string.
func functionFailureTypeAlias(fn FunctionSignature) string {
	ft := effectFailureType(fn)
	if strings.Contains(ft, " | ") {
		return fn.Name + "Failure"
	}
	return ft
}

func emitFunctionFailureAliases(b *strings.Builder, functions []FunctionSignature) {
	for _, fn := range functions {
		ft := effectFailureType(fn)
		if !strings.Contains(ft, " | ") {
			continue
		}
		fmt.Fprintf(b, "export type %sFailure = %s;\n\n", fn.Name, ft)
	}
}

func failureTypeIdentNames(failureType string) []string {
	if failureType == "" || failureType == "InvokeFailure" {
		return []string{"InvokeFailure"}
	}
	return sortDedupeStrings(strings.Split(failureType, " | "))
}

func collectFailureTypeImports(functions []FunctionSignature) []string {
	var names []string
	for _, fn := range functions {
		names = append(names, failureTypeIdentNames(effectFailureType(fn))...)
	}
	return sortDedupeStrings(names)
}

func isInvokeCatalogName(name string) bool {
	if name == "InvokeFailure" {
		return true
	}
	for _, c := range ErrorCatalog {
		if c.Name == name {
			return true
		}
	}
	return false
}

func splitFailureTypeImports(functions []FunctionSignature) (domain []string, invoke []string) {
	for _, name := range collectFailureTypeImports(functions) {
		if isInvokeCatalogName(name) {
			invoke = append(invoke, name)
		} else {
			domain = append(domain, name)
		}
	}
	return sortDedupeStrings(domain), sortDedupeStrings(invoke)
}

func writeFailureTypeImports(b *strings.Builder, functions []FunctionSignature, errorsModule string) {
	domain, invoke := splitFailureTypeImports(functions)
	if len(domain) > 0 {
		fmt.Fprintf(b, `import type { %s } from %q;`+"\n", strings.Join(domain, ", "), errorsModule)
	}
	if len(invoke) > 0 {
		fmt.Fprintf(b, `import type { %s } from %q;`+"\n", strings.Join(invoke, ", "), "../errors.js")
	}
}

func domainErrorsModuleForCore(m ModuleEmit) string {
	if len(m.DomainErrors) == 0 {
		return "../errors.js"
	}
	return "../pkg/" + PackageDomainErrorsFileStem(m.PackageName) + ".js"
}

func domainErrorsModuleForPkg(m ModuleEmit) string {
	if len(m.DomainErrors) == 0 {
		return "../errors.js"
	}
	return "./" + PackageDomainErrorsFileStem(m.PackageName) + ".js"
}

func writeErrorsTypeImport(b *strings.Builder, functions []FunctionSignature, module string) {
	writeErrorsTypeImportExcluding(b, functions, module, nil)
}

func writeErrorsTypeImportExcluding(b *strings.Builder, functions []FunctionSignature, module string, exclude map[string]struct{}) {
	names := collectFailureTypeImports(functions)
	filtered := make([]string, 0, len(names))
	for _, name := range names {
		if exclude != nil {
			if _, skip := exclude[name]; skip {
				continue
			}
		}
		filtered = append(filtered, name)
	}
	if len(filtered) == 0 {
		return
	}
	fmt.Fprintf(b, `import type { %s } from %q;`+"\n", strings.Join(filtered, ", "), module)
}

func writeTestingErrorsImports(b *strings.Builder, functions []FunctionSignature) {
	exclude := map[string]struct{}{
		"ForstTestServerFailed": {},
		"InvokeRejected":        {},
	}
	domain, invoke := splitFailureTypeImports(functions)
	filter := func(names []string) []string {
		out := make([]string, 0, len(names))
		for _, name := range names {
			if _, skip := exclude[name]; skip {
				continue
			}
			out = append(out, name)
		}
		return out
	}
	domain = filter(domain)
	invoke = filter(invoke)
	fmt.Fprintf(b, "import { InvokeRejected } from %q;\n", errorsPackageImport(RuntimeEffect))
	if len(domain) > 0 {
		fmt.Fprintf(b, `import type { %s } from "./errors.js";`+"\n", strings.Join(domain, ", "))
	}
	if len(invoke) > 0 {
		fmt.Fprintf(b, `import type { %s } from "./errors.js";`+"\n", strings.Join(invoke, ", "))
	}
}

// EmitPackageEffectDTS returns dist/pkg/<pkg>.d.ts for Effect mode.
func EmitPackageEffectDTS(m ModuleEmit, npmPackageName string) string {
	pkg := m.PackageName
	className := ServiceClassName(pkg)
	tag := effectTagPrefix(npmPackageName) + "/" + className
	typeImports := sortDedupeStrings(m.TypeImports)
	var b strings.Builder
	b.WriteString("// Auto-generated public module for " + pkg + " package\n")
	b.WriteString("// Generated by Forst TypeScript Transformer\n")
	b.WriteString("// Effect mode: wraps identical core Promise implementation.\n\n")
	b.WriteString(`import { Context, Effect, Layer } from "effect";` + "\n")
	b.WriteString(`import type { ForstInvokeClient, InvokeCallOptions } from "../transport.js";` + "\n")
	b.WriteString(`import { ForstTransport } from "../effect.js";` + "\n")
writeFailureTypeImports(&b, m.Functions, domainErrorsModuleForPkg(m))
	typeNames := append([]string(nil), typeImports...)
	if functionsNeedStreamingResult(m.Functions) {
		typeNames = append(typeNames, "StreamingResult")
		typeNames = sortDedupeStrings(typeNames)
	}
	if len(typeNames) > 0 {
		b.WriteString(fmt.Sprintf("import type { %s } from \"../types.js\";\n", strings.Join(typeNames, ", ")))
	}
	b.WriteString("\n")

	b.WriteString("/** Per-call options in Effect mode. retries is omitted; use Effect.retry. */\n")
	b.WriteString("export type EffectInvokeCallOptions = Omit<InvokeCallOptions, \"retries\">;\n\n")

	emitFunctionFailureAliases(&b, m.Functions)

	// Namespace factory type from core (createForstClient).
	b.WriteString(fmt.Sprintf("export declare const %s: (client: ForstInvokeClient) => {\n", pkg))
	for _, fn := range m.Functions {
		params := emitParamListDTS(fn.Parameters, true)
		b.WriteString(fmt.Sprintf("  %s: (%s) => Promise<%s>;\n", fn.Name, params, fn.ReturnType))
		if fn.StreamingRowType != "" {
			b.WriteString(fmt.Sprintf(
				"  %sStream: (%s) => AsyncGenerator<StreamingResult & { data?: %s }, void, undefined>;\n",
				fn.Name, params, fn.StreamingRowType,
			))
		}
	}
	b.WriteString("};\n\n")

	// Ambient Tag form avoids TS1005 from type args inside Effect.Service() value args.
	// Runtime JS still emits Effect.Service with accessors and dependencies.
	b.WriteString(fmt.Sprintf("export declare class %s extends Context.Tag(%q)<\n", className, tag))
	b.WriteString(fmt.Sprintf("  %s,\n", className))
	b.WriteString("  {\n")
	for _, fn := range m.Functions {
		params := emitEffectParamListDTS(fn.Parameters)
		b.WriteString(fmt.Sprintf(
			"    readonly %s: (%s) => Effect.Effect<%s, %s>;\n",
			fn.Name, params, fn.ReturnType, functionFailureTypeAlias(fn),
		))
	}
	b.WriteString("  }\n")
	b.WriteString(">() {\n")
	b.WriteString(fmt.Sprintf("  static readonly Default: Layer.Layer<%s>;\n", className))
	b.WriteString(fmt.Sprintf(
		"  static readonly DefaultWithoutDependencies: Layer.Layer<%s, never, ForstTransport>;\n",
		className,
	))
	for _, fn := range m.Functions {
		params := emitEffectParamListDTS(fn.Parameters)
		b.WriteString(fmt.Sprintf(
			"  static readonly %s: (%s) => Effect.Effect<%s, %s, %s>;\n",
			fn.Name, params, fn.ReturnType, functionFailureTypeAlias(fn), className,
		))
	}
	b.WriteString("}\n\n")

	for _, fn := range m.Functions {
		params := emitEffectParamListDTS(fn.Parameters)
		b.WriteString(fmt.Sprintf("export declare const %s: (\n", fn.Name))
		b.WriteString(fmt.Sprintf("  %s\n", params))
		b.WriteString(fmt.Sprintf(
			") => Effect.Effect<%s, %s, %s>;\n\n",
			fn.ReturnType, functionFailureTypeAlias(fn), className,
		))
		if fn.StreamingRowType != "" {
			streamParams := emitParamListDTS(fn.Parameters, true)
			b.WriteString(fmt.Sprintf("export declare function %sStream(\n", fn.Name))
			b.WriteString(fmt.Sprintf("  %s\n", streamParams))
			b.WriteString(fmt.Sprintf(
				"): AsyncGenerator<StreamingResult & { data?: %s }, void, undefined>;\n\n",
				fn.StreamingRowType,
			))
		}
	}

	if len(typeImports) > 0 {
		b.WriteString(fmt.Sprintf("export type { %s } from \"../types.js\";\n", strings.Join(typeImports, ", ")))
	}
	appendOmitStubs(&b, m.Omitted)
	return b.String()
}

func emitEffectParamListDTS(params []Parameter) string {
	parts := make([]string, 0, len(params)+1)
	for _, p := range params {
		parts = append(parts, fmt.Sprintf("%s: %s", p.Name, p.Type))
	}
	parts = append(parts, "options?: EffectInvokeCallOptions")
	return strings.Join(parts, ", ")
}

// EmitIndexEffectESM appends Effect root layers onto the Promise index body.
func EmitIndexEffectESM(packages []string, npmPackageName string) string {
	pkgs := sortDedupeStrings(packages)
	var b strings.Builder
	b.WriteString("\n// --- Effect mode root layers ---\n")
	b.WriteString(`import { Layer, ManagedRuntime } from "effect";` + "\n")
	b.WriteString(`import { ForstTransportLayer } from "./effect.js";` + "\n")
	for _, pkg := range pkgs {
		className := ServiceClassName(pkg)
		b.WriteString(fmt.Sprintf("import { %s } from \"./pkg/%s.js\";\n", className, pkg))
	}
	b.WriteString("\n")

	if len(pkgs) == 0 {
		b.WriteString("export const ForstClientLive = Layer.empty;\n\n")
		b.WriteString("export const ForstClientLayer = (config) =>\n")
		b.WriteString("  Layer.provide(Layer.empty, ForstTransportLayer(config));\n\n")
		b.WriteString("export const makeForstClientRuntime = (config) =>\n")
		b.WriteString("  ManagedRuntime.make(ForstClientLayer(config));\n")
		return b.String()
	}

	defaults := make([]string, len(pkgs))
	withoutDeps := make([]string, len(pkgs))
	for i, pkg := range pkgs {
		className := ServiceClassName(pkg)
		defaults[i] = className + ".Default"
		withoutDeps[i] = className + ".DefaultWithoutDependencies"
	}
	b.WriteString(fmt.Sprintf("export const ForstClientLive = Layer.mergeAll(%s);\n\n", strings.Join(defaults, ", ")))
	b.WriteString("export const ForstClientLayer = (config) => {\n")
	b.WriteString("  const transportLayer = ForstTransportLayer(config);\n")
	b.WriteString(fmt.Sprintf("  return Layer.mergeAll(%s).pipe(\n", strings.Join(withoutDeps, ", ")))
	b.WriteString("    Layer.provide(transportLayer)\n")
	b.WriteString("  );\n")
	b.WriteString("};\n\n")
	b.WriteString("export const makeForstClientRuntime = (config) =>\n")
	b.WriteString("  ManagedRuntime.make(ForstClientLayer(config));\n")
	_ = npmPackageName
	return b.String()
}

// EmitIndexEffectDTS appends Effect root declarations onto the Promise index .d.ts.
func EmitIndexEffectDTS(packages []string) string {
	pkgs := sortDedupeStrings(packages)
	var b strings.Builder
	b.WriteString("\n// --- Effect mode root layers ---\n")
	b.WriteString(`import { Layer, ManagedRuntime } from "effect";` + "\n")
	serviceTypes := make([]string, 0, len(pkgs))
	for _, pkg := range pkgs {
		className := ServiceClassName(pkg)
		b.WriteString(fmt.Sprintf("import { %s } from \"./pkg/%s.js\";\n", className, pkg))
		serviceTypes = append(serviceTypes, className)
	}
	b.WriteString("\n")
	req := "never"
	if len(serviceTypes) > 0 {
		req = strings.Join(serviceTypes, " | ")
	}
	b.WriteString(fmt.Sprintf("export declare const ForstClientLive: Layer.Layer<%s>;\n\n", req))
	b.WriteString("export declare const ForstClientLayer: (\n")
	b.WriteString("  config?: ForstInvokeClientConfig\n")
	b.WriteString(fmt.Sprintf(") => Layer.Layer<%s>;\n\n", req))
	b.WriteString("export declare const makeForstClientRuntime: (\n")
	b.WriteString("  config?: ForstInvokeClientConfig\n")
	b.WriteString(fmt.Sprintf(") => ManagedRuntime.ManagedRuntime<%s, never>;\n", req))
	return b.String()
}

// EmitTestingEffectESM returns dist/testing.js for Effect mode (ForstTestLayer + ForstTestServerLayer).
func EmitTestingEffectESM(modules []ModuleEmit, npmPackageName string) string {
	mods := sortModulesByPackage(modules)
	tagPrefix := effectTagPrefix(npmPackageName)
	var b strings.Builder
	b.WriteString(`// Auto-generated Forst Effect test layers.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

import { Context, Effect, Layer, ManagedRuntime } from "effect";
import { ForstTransportLayer } from "./effect.js";
`)
	fmt.Fprintf(&b, "import { InvokeRejected } from %q;\n", errorsPackageImport(RuntimeEffect))
	b.WriteString(EmitHarnessErrorESM(npmPackageName, RuntimeEffect))
	b.WriteString("\n")
	for _, m := range mods {
		pkg := m.PackageName
		if pkg == "" {
			continue
		}
		className := ServiceClassName(pkg)
		fmt.Fprintf(&b, "import { %s } from \"./pkg/%s.js\";\n", className, pkg)
	}
	b.WriteString("\n")
	b.WriteString(testingEffectRuntimeESM)
	b.WriteString("\n")
	emitTestServerStartHelperESM(&b)
	b.WriteString("\n")
	fmt.Fprintf(&b, "export class ForstTestServer extends Context.Tag(%q)() {}\n\n", tagPrefix+"/TestServer")
	b.WriteString("export function ForstTestLayer(overrides) {\n")
	b.WriteString("  const packages = overrides?.packages ?? {};\n")
	b.WriteString("  const layers = [];\n")
	for _, m := range mods {
		pkg := m.PackageName
		if pkg == "" {
			continue
		}
		className := ServiceClassName(pkg)
		fmt.Fprintf(&b, "  layers.push(mockPackageLayer(%s, packages[%q]));\n", className, pkg)
	}
	b.WriteString("  if (layers.length === 0) {\n")
	b.WriteString("    return Layer.empty;\n")
	b.WriteString("  }\n")
	b.WriteString("  return Layer.mergeAll(...layers);\n")
	b.WriteString("}\n\n")

	b.WriteString("const forstTestServerScopedLayer = (options) =>\n")
	b.WriteString("  Layer.scoped(\n")
	b.WriteString("    ForstTestServer,\n")
	b.WriteString("    Effect.acquireRelease(\n")
	b.WriteString("      Effect.tryPromise({\n")
	b.WriteString("        try: () => startInvokeServerHandle(options),\n")
	b.WriteString("        catch: (error) =>\n")
	b.WriteString("          error instanceof ForstTestServerFailed\n")
	b.WriteString("            ? error\n")
	b.WriteString("            : new ForstTestServerFailed({\n")
	b.WriteString("                reason: \"spawn_failed\",\n")
	b.WriteString("                causeMessage: String(error?.message ?? error),\n")
	b.WriteString("                message: String(error?.message ?? error),\n")
	b.WriteString("              }),\n")
	b.WriteString("      }).pipe(\n")
	b.WriteString("        Effect.map((handle) => ({\n")
	b.WriteString("          baseUrl: handle.baseUrl,\n")
	b.WriteString("          port: handle.port,\n")
	b.WriteString("          pid: handle.pid,\n")
	b.WriteString("          connection: handle.connection,\n")
	b.WriteString("          auth: handle.auth,\n")
	b.WriteString("          stop: () => handle.stop(),\n")
	b.WriteString("        }))\n")
	b.WriteString("      ),\n")
	b.WriteString("      (svc) => Effect.promise(() => svc.stop())\n")
	b.WriteString("    )\n")
	b.WriteString("  );\n\n")

	b.WriteString("export function ForstTestServerLayer(options) {\n")
	b.WriteString("  const base = forstTestServerScopedLayer(options);\n")
	b.WriteString("  const transport = Layer.unwrapEffect(\n")
	b.WriteString("    Effect.map(ForstTestServer, ({ baseUrl, auth }) =>\n")
	b.WriteString("      ForstTransportLayer({\n")
	b.WriteString("        baseUrl,\n")
	b.WriteString("        rootDir: options?.root ?? process.cwd(),\n")
	b.WriteString("        ...(auth\n")
	b.WriteString("          ? {\n")
	b.WriteString("              resolveAuth: () => ({\n")
	b.WriteString("                token: auth.token,\n")
	b.WriteString("                generation: auth.generation,\n")
	b.WriteString("              }),\n")
	b.WriteString("            }\n")
	b.WriteString("          : {}),\n")
	b.WriteString("      })\n")
	b.WriteString("    )\n")
	b.WriteString("  ).pipe(Layer.provide(base));\n")
	withoutDeps := make([]string, 0, len(mods))
	for _, m := range mods {
		pkg := m.PackageName
		if pkg == "" {
			continue
		}
		withoutDeps = append(withoutDeps, ServiceClassName(pkg)+".DefaultWithoutDependencies")
	}
	if len(withoutDeps) == 0 {
		b.WriteString("  return Layer.mergeAll(transport, base);\n")
	} else {
		b.WriteString(fmt.Sprintf("  return Layer.mergeAll(%s)\n", strings.Join(withoutDeps, ", ")))
		b.WriteString("    .pipe(Layer.provide(transport), Layer.merge(base));\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("export const makeForstTestServer = (options) =>\n")
	b.WriteString("  ManagedRuntime.make(ForstTestServerLayer(options));\n\n")
	b.WriteString("export { InvokeRejected };\n")
	return b.String()
}

// EmitTestingEffectDTS returns dist/testing.d.ts for Effect mode.
func EmitTestingEffectDTS(modules []ModuleEmit, npmPackageName string) string {
	mods := sortModulesByPackage(modules)
	tagPrefix := effectTagPrefix(npmPackageName)
	typeImports := collectTestingTypeImports(mods)
	var allFns []FunctionSignature
	for _, m := range mods {
		allFns = append(allFns, m.Functions...)
	}
	var b strings.Builder
	b.WriteString(`// Auto-generated Forst Effect test layers.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

`)
	b.WriteString(EmitHarnessErrorDTS(npmPackageName, RuntimeEffect))
	b.WriteString("\n")
	b.WriteString(`import { Context, Effect, Layer, ManagedRuntime } from "effect";
import type {
  ForstInvokeClient,
  InvokeCallOptions,
} from "./transport.js";
`)
	writeTestingErrorsImports(&b, allFns)
	b.WriteString(`
export { InvokeRejected };
`)
	if len(typeImports) > 0 {
		fmt.Fprintf(&b, "import type { %s } from \"./types.js\";\n", strings.Join(typeImports, ", "))
	}
	serviceTypes := make([]string, 0, len(mods))
	for _, m := range mods {
		pkg := m.PackageName
		if pkg == "" {
			continue
		}
		className := ServiceClassName(pkg)
		fmt.Fprintf(&b, "import { %s } from \"./pkg/%s.js\";\n", className, pkg)
		serviceTypes = append(serviceTypes, className)
	}
	b.WriteString("\n")

	for _, m := range mods {
		pkg := m.PackageName
		if pkg == "" {
			continue
		}
		fmt.Fprintf(&b, "export type %s = {\n", handlersTypeName(pkg))
		for _, fn := range m.Functions {
			params := emitParamListDTS(fn.Parameters, true)
			fmt.Fprintf(&b, "  %s: (%s) =>\n", fn.Name, params)
			fmt.Fprintf(&b, "    | %s\n", fn.ReturnType)
			fmt.Fprintf(&b, "    | Promise<%s>\n", fn.ReturnType)
			fmt.Fprintf(&b, "    | Effect.Effect<%s, %s>;\n", fn.ReturnType, effectFailureType(fn))
			if fn.StreamingRowType != "" {
				fmt.Fprintf(&b,
					"  %sStream: (%s) => AsyncGenerator<import(\"./transport.js\").StreamingResult & { data?: %s }, void, undefined>;\n",
					fn.Name, params, fn.StreamingRowType,
				)
			}
		}
		b.WriteString("};\n\n")
	}

	b.WriteString("export interface ForstTestOverrides {\n")
	b.WriteString("  /** Replace whole packages or single functions. Both levels use this map. */\n")
	b.WriteString("  packages?: {\n")
	for _, m := range mods {
		pkg := m.PackageName
		if pkg == "" {
			continue
		}
		fmt.Fprintf(&b, "    %s?: Partial<%s>;\n", pkg, handlersTypeName(pkg))
	}
	b.WriteString("  };\n")
	b.WriteString("  /** Replace the raw invoke calls, to assert on the wire or simulate failures. */\n")
	b.WriteString("  transport?: Partial<ForstInvokeClient>;\n")
	b.WriteString("}\n\n")

	req := "never"
	if len(serviceTypes) > 0 {
		req = strings.Join(serviceTypes, " | ")
	}
	b.WriteString("export declare const ForstTestLayer: (\n")
	b.WriteString("  overrides: ForstTestOverrides\n")
	b.WriteString(fmt.Sprintf(") => Layer.Layer<%s>;\n\n", req))

	emitForstTestServerOptionsDTS(&b)
	fmt.Fprintf(&b, "export declare class ForstTestServer extends Context.Tag(%q)<\n", tagPrefix+"/TestServer")
	b.WriteString("  ForstTestServer,\n")
	b.WriteString("  {\n")
	b.WriteString("    readonly baseUrl: string;\n")
	b.WriteString("    readonly port: number;\n")
	b.WriteString("    readonly pid?: number;\n")
	b.WriteString("    readonly connection: \"spawn\" | \"connect\";\n")
	b.WriteString("  }\n")
	b.WriteString(">() {}\n\n")

	serverReq := "ForstTestServer"
	if len(serviceTypes) > 0 {
		serverReq = strings.Join(serviceTypes, " | ") + " | ForstTestServer"
	}
	b.WriteString("export declare const ForstTestServerLayer: (\n")
	b.WriteString("  options?: ForstTestServerOptions\n")
	b.WriteString(fmt.Sprintf(") => Layer.Layer<%s, ForstTestServerFailed>;\n\n", serverReq))
	b.WriteString("export declare const makeForstTestServer: (\n")
	b.WriteString("  options?: ForstTestServerOptions\n")
	b.WriteString(fmt.Sprintf(") => ManagedRuntime.ManagedRuntime<%s, ForstTestServerFailed>;\n", serverReq))
	return b.String()
}

const testingEffectRuntimeESM = `function normalizeHandlerResult(result) {
  if (Effect.isEffect(result)) {
    return result;
  }
  return Effect.tryPromise({
    try: () => Promise.resolve(result),
    catch: (error) => error,
  });
}

function mockPackageLayer(service, handlers) {
  if (!handlers || typeof handlers !== "object") {
    return Layer.mock(service, {});
  }
  const partial = {};
  for (const [name, handler] of Object.entries(handlers)) {
    if (typeof handler !== "function") {
      continue;
    }
    partial[name] = (...args) => normalizeHandlerResult(handler(...args));
  }
  return Layer.mock(service, partial);
}
`
