package transformerts

import (
	"fmt"
	"sort"
	"strings"
)

// ModuleEmit is the per-package input for dist/core and dist/pkg JS/DTS emit templates.
// PackageName is both the RPC package name and the generated module stem.
type ModuleEmit struct {
	PackageName string
	Functions   []FunctionSignature
	TypeImports []string
	// Omitted holds provider-gated functions for optional commented stubs (omitStubs).
	Omitted []OmittedFunction
}

// ModuleEmitFromOutput maps a transformer package output to ModuleEmit.
// When omitStubs is true, provider-gated omissions are attached for commented stubs.
func ModuleEmitFromOutput(out *TypeScriptOutput, omitStubs bool) ModuleEmit {
	pkg := out.PackageName
	if pkg == "" {
		pkg = out.SourceFileStem
	}
	mod := ModuleEmit{
		PackageName: pkg,
		Functions:   out.Functions,
		TypeImports: append([]string(nil), out.ExportedTypeNames...),
	}
	if omitStubs && len(out.OmittedFunctions) > 0 {
		mod.Omitted = append([]OmittedFunction(nil), out.OmittedFunctions...)
	}
	return mod
}

// packageModuleRuntimeComment documents how Promise and Effect modes share one core implementation.
const packageModuleRuntimeComment = "// Promise mode re-exports core. Effect mode wraps the same core.\n\n"

// GeneratedHeaderComment returns the FORST_BASE_URL hint with the resolved invoke port (F-10).
func GeneratedHeaderComment(invokePort string) string {
	port := invokePort
	if port == "" {
		port = DefaultInvokePort
	}
	return fmt.Sprintf("// Embedded invoke: set FORST_BASE_URL=http://127.0.0.1:%s\n", port)
}

// generatedHeaderComment is kept as an unexported alias for call sites inside this package.
func generatedHeaderComment(invokePort string) string {
	return GeneratedHeaderComment(invokePort)
}

// emitInvokeCall renders a transport invokeFunction call.
// argExpr is the comma-separated contents of the args array (may be empty).
func emitInvokeCall(pkg, fn string, argExpr string) string {
	return fmt.Sprintf(`client.invokeFunction(%q, %q, [%s], options)`, pkg, fn, argExpr)
}

// emitInvokeStreamCall renders a transport invokeStream call.
func emitInvokeStreamCall(pkg, fn string, argExpr string) string {
	return fmt.Sprintf(`client.invokeStream(%q, %q, [%s], options)`, pkg, fn, argExpr)
}

func emitArgExpr(params []Parameter) string {
	if len(params) == 0 {
		return ""
	}
	names := make([]string, len(params))
	for i, p := range params {
		names[i] = p.Name
	}
	return strings.Join(names, ", ")
}

func emitParamListJS(params []Parameter, includeOptions bool) string {
	parts := make([]string, 0, len(params)+1)
	for _, p := range params {
		parts = append(parts, p.Name)
	}
	if includeOptions {
		parts = append(parts, "options")
	}
	return strings.Join(parts, ", ")
}

func emitParamListDTS(params []Parameter, includeOptions bool) string {
	parts := make([]string, 0, len(params)+1)
	for _, p := range params {
		parts = append(parts, fmt.Sprintf("%s: %s", p.Name, p.Type))
	}
	if includeOptions {
		parts = append(parts, "options?: InvokeCallOptions")
	}
	return strings.Join(parts, ", ")
}

// EmitCoreESM returns dist/core/<pkg>.js (Promise implementation).
// Identical in Promise and Effect modes. No runtime mode argument.
func EmitCoreESM(m ModuleEmit, invokePort string) string {
	pkg := m.PackageName
	var b strings.Builder
	b.WriteString("// Auto-generated client for " + pkg + " package\n")
	b.WriteString("// Generated by Forst TypeScript Transformer\n")
	b.WriteString("// Do not edit by hand.\n")
	b.WriteString(generatedHeaderComment(invokePort))
	b.WriteString("\n")
	b.WriteString(`import { getDefaultInvokeClient } from "../transport.js";` + "\n\n")

	// Namespace factory for createForstClient (root index binds client once).
	b.WriteString(fmt.Sprintf("export const %s = (client) => ({\n", pkg))
	for _, fn := range m.Functions {
		argExpr := emitArgExpr(fn.Parameters)
		params := emitParamListJS(fn.Parameters, true)
		b.WriteString(fmt.Sprintf("  %s: async (%s) => {\n", fn.Name, params))
		b.WriteString(fmt.Sprintf("    const response = await %s;\n", emitInvokeCall(pkg, fn.Name, argExpr)))
		b.WriteString("    return response.result;\n")
		b.WriteString("  },\n")
		if fn.StreamingRowType != "" {
			b.WriteString(fmt.Sprintf("  %sStream: (%s) =>\n", fn.Name, params))
			b.WriteString(fmt.Sprintf("    %s,\n", emitInvokeStreamCall(pkg, fn.Name, argExpr)))
		}
	}
	b.WriteString("});\n\n")

	// Flat named exports with options.transport seam (SPEC §6.1).
	for _, fn := range m.Functions {
		argExpr := emitArgExpr(fn.Parameters)
		params := emitParamListJS(fn.Parameters, true)
		b.WriteString(fmt.Sprintf("export async function %s(%s) {\n", fn.Name, params))
		b.WriteString("  const client = options?.transport ?? getDefaultInvokeClient();\n")
		b.WriteString(fmt.Sprintf("  const response = await %s;\n", emitInvokeCall(pkg, fn.Name, argExpr)))
		b.WriteString("  return response.result;\n")
		b.WriteString("}\n\n")
		b.WriteString(fmt.Sprintf("%s.safe = async (%s) => {\n", fn.Name, params))
		b.WriteString("  try {\n")
		b.WriteString(fmt.Sprintf("    return { ok: true, value: await %s(%s) };\n", fn.Name, params))
		b.WriteString("  } catch (error) {\n")
		b.WriteString("    return { ok: false, error };\n")
		b.WriteString("  }\n")
		b.WriteString("};\n\n")
		if fn.StreamingRowType != "" {
			b.WriteString(fmt.Sprintf("export function %sStream(%s) {\n", fn.Name, params))
			b.WriteString("  const client = options?.transport ?? getDefaultInvokeClient();\n")
			b.WriteString(fmt.Sprintf("  return %s;\n", emitInvokeStreamCall(pkg, fn.Name, argExpr)))
			b.WriteString("}\n\n")
		}
	}

	return b.String()
}

// EmitCoreDTS returns dist/core/<pkg>.d.ts.
func EmitCoreDTS(m ModuleEmit) string {
	pkg := m.PackageName
	typeImports := sortDedupeStrings(m.TypeImports)
	var b strings.Builder
	b.WriteString("// Auto-generated client for " + pkg + " package\n")
	b.WriteString("// Generated by Forst TypeScript Transformer\n")
	b.WriteString("// Do not edit by hand.\n\n")
	b.WriteString(`import type { ForstInvokeClient, InvokeCallOptions } from "../transport.js";` + "\n")
	writeFailureTypeImports(&b, m.Functions, "../errors.js")
	typeNames := append([]string(nil), typeImports...)
	if functionsNeedStreamingResult(m.Functions) {
		typeNames = append(typeNames, "StreamingResult")
		typeNames = sortDedupeStrings(typeNames)
	}
	if len(typeNames) > 0 {
		b.WriteString(fmt.Sprintf("import type { %s } from \"../types.js\";\n", strings.Join(typeNames, ", ")))
	}
	b.WriteString("\n")

	b.WriteString(fmt.Sprintf("export declare const %s: (client: ForstInvokeClient) => {\n", pkg))
	for _, fn := range m.Functions {
		params := emitParamListDTS(fn.Parameters, true)
		b.WriteString(fmt.Sprintf("  %s: (%s) => Promise<%s>;\n", fn.Name, params, fn.ReturnType))
		if fn.StreamingRowType != "" {
			b.WriteString(fmt.Sprintf(
				"  %sStream: (%s) => AsyncGenerator<StreamingResult & { data?: %s }, void, undefined>;\n",
				fn.Name, params, fn.StreamingRowType,
			))
		}
	}
	b.WriteString("};\n\n")

	emitFunctionFailureAliases(&b, m.Functions)

	for _, fn := range m.Functions {
		params := emitParamListDTS(fn.Parameters, true)
		b.WriteString(fmt.Sprintf("/** @throws {%s} */\n", functionFailureTypeAlias(fn)))
		b.WriteString(fmt.Sprintf("export declare function %s(\n", fn.Name))
		b.WriteString(fmt.Sprintf("  %s\n", params))
		b.WriteString(fmt.Sprintf("): Promise<%s>;\n\n", fn.ReturnType))
		b.WriteString(fmt.Sprintf("export declare namespace %s {\n", fn.Name))
		b.WriteString("  function safe(\n")
		b.WriteString(fmt.Sprintf("    %s\n", params))
		b.WriteString("  ): Promise<\n")
		b.WriteString(fmt.Sprintf("    | { ok: true; value: %s }\n", fn.ReturnType))
		b.WriteString("    | { ok: false; error: " + functionFailureTypeAlias(fn) + " }\n")
		b.WriteString("  >;\n")
		b.WriteString("}\n\n")
		if fn.StreamingRowType != "" {
			b.WriteString(fmt.Sprintf("export declare function %sStream(\n", fn.Name))
			b.WriteString(fmt.Sprintf("  %s\n", params))
			b.WriteString(fmt.Sprintf(
				"): AsyncGenerator<StreamingResult & { data?: %s }, void, undefined>;\n\n",
				fn.StreamingRowType,
			))
		}
	}

	return b.String()
}

// EmitPackageESM returns dist/pkg/<pkg>.js.
// Promise mode re-exports core. Effect mode wraps the same core with Effect.Service.
// This is the only Emit* function (with EmitPackageDTS) that takes ClientRuntime.
func EmitPackageESM(m ModuleEmit, runtime ClientRuntime, npmPackageName string) string {
	if runtime == RuntimeEffect {
		return EmitPackageEffectESM(m, npmPackageName)
	}
	pkg := m.PackageName
	var b strings.Builder
	b.WriteString("// Auto-generated public module for " + pkg + " package\n")
	b.WriteString("// Generated by Forst TypeScript Transformer\n")
	b.WriteString(packageModuleRuntimeComment)
	b.WriteString(fmt.Sprintf("export * from \"../core/%s.js\";\n", pkg))
	appendOmitStubs(&b, m.Omitted)
	return b.String()
}

// EmitPackageDTS returns dist/pkg/<pkg>.d.ts.
// This is the only Emit* function (with EmitPackageESM) that takes ClientRuntime.
func EmitPackageDTS(m ModuleEmit, runtime ClientRuntime, npmPackageName string) string {
	if runtime == RuntimeEffect {
		return EmitPackageEffectDTS(m, npmPackageName)
	}
	pkg := m.PackageName
	typeImports := sortDedupeStrings(m.TypeImports)
	var b strings.Builder
	b.WriteString("// Auto-generated public module for " + pkg + " package\n")
	b.WriteString("// Generated by Forst TypeScript Transformer\n")
	b.WriteString(packageModuleRuntimeComment)
	b.WriteString(fmt.Sprintf("export * from \"../core/%s.js\";\n", pkg))
	if len(typeImports) > 0 {
		b.WriteString(fmt.Sprintf("export type { %s } from \"../types.js\";\n", strings.Join(typeImports, ", ")))
	}
	appendOmitStubs(&b, m.Omitted)
	return b.String()
}

// appendOmitStubs writes commented stubs for provider-gated omissions (SPEC §12).
func appendOmitStubs(b *strings.Builder, omitted []OmittedFunction) {
	if b == nil || len(omitted) == 0 {
		return
	}
	sorted := append([]OmittedFunction(nil), omitted...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].PackageName != sorted[j].PackageName {
			return sorted[i].PackageName < sorted[j].PackageName
		}
		return sorted[i].FunctionName < sorted[j].FunctionName
	})
	b.WriteString("\n")
	for _, o := range sorted {
		decl := o.ExportDecl
		if decl == "" {
			decl = fmt.Sprintf("export function %s();", o.FunctionName)
		}
		b.WriteString("// " + decl + "\n")
		b.WriteString("// omitted: " + o.Reason + "\n")
	}
}

// EmitIndexESM returns dist/index.js (createForstClient factory + error re-exports).
func EmitIndexESM(packages []string, invokePort string, domainErrors []ErrorClass, runtime ClientRuntime) string {
	pkgs := sortDedupeStrings(packages)
	var b strings.Builder
	b.WriteString("// Auto-generated Forst Client\n")
	b.WriteString("// Generated by Forst TypeScript Transformer\n")
	b.WriteString("// Do not edit by hand.\n")
	b.WriteString(generatedHeaderComment(invokePort))
	b.WriteString("\n")
	b.WriteString(`import { createInvokeClient, configureDefaultInvokeClient } from "./transport.js";` + "\n")
	for _, pkg := range pkgs {
		b.WriteString(fmt.Sprintf("import { %s } from \"./pkg/%s.js\";\n", pkg, pkg))
	}
	b.WriteString("\n")
	b.WriteString("export function createForstClient(config) {\n")
	b.WriteString("  const client = createInvokeClient(config);\n")
	b.WriteString("  return {\n")
	for _, pkg := range pkgs {
		b.WriteString(fmt.Sprintf("    %s: %s(client),\n", pkg, pkg))
	}
	b.WriteString("  };\n")
	b.WriteString("}\n\n")
	b.WriteString("export { configureDefaultInvokeClient };\n\n")
	b.WriteString("export {\n")
	for _, name := range RootReexportedDomainErrorNames(domainErrors) {
		fmt.Fprintf(&b, "  %s,\n", name)
	}
	b.WriteString(`} from "./errors.js";` + "\n")
	return b.String()
}

// EmitIndexDTS returns dist/index.d.ts.
func EmitIndexDTS(packages []string, domainErrors []ErrorClass, runtime ClientRuntime) string {
	domainErrors = MergeDomainErrors(domainErrors)
	pkgs := sortDedupeStrings(packages)
	var b strings.Builder
	b.WriteString("// Auto-generated Forst Client\n")
	b.WriteString("// Generated by Forst TypeScript Transformer\n")
	b.WriteString("// Do not edit by hand.\n\n")
	b.WriteString(`import type {
  ForstInvokeClientConfig,
  ForstInvokeMiddleware,
  InvokeCallOptions,
  InvokeContext,
} from "./transport.js";
` + "\n")
	for _, pkg := range pkgs {
		b.WriteString(fmt.Sprintf("import { %s } from \"./pkg/%s.js\";\n", pkg, pkg))
	}
	b.WriteString("\n")
	b.WriteString("export interface ForstClientConfig {\n")
	b.WriteString("  baseUrl?: string;\n")
	b.WriteString("  /** Alias accepted for parity with older clients. */\n")
	b.WriteString("  devServerUrl?: string;\n")
	b.WriteString("  timeout?: number;\n")
	b.WriteString("  retries?: number;\n")
	b.WriteString("  middleware?: ForstInvokeMiddleware[];\n")
	b.WriteString("}\n\n")
	b.WriteString("export declare function createForstClient(\n")
	b.WriteString("  config?: ForstClientConfig | ForstInvokeClientConfig\n")
	b.WriteString("): {\n")
	for _, pkg := range pkgs {
		b.WriteString(fmt.Sprintf("  readonly %s: ReturnType<typeof %s>;\n", pkg, pkg))
	}
	b.WriteString("};\n\n")
	b.WriteString("export type ForstClient = ReturnType<typeof createForstClient>;\n\n")
	b.WriteString("export declare function configureDefaultInvokeClient(\n")
	b.WriteString("  config: ForstInvokeClientConfig\n")
	b.WriteString("): void;\n\n")
	b.WriteString("export type {\n")
	b.WriteString("  InvokeCallOptions,\n")
	b.WriteString("  ForstInvokeClientConfig,\n")
	b.WriteString("  ForstInvokeMiddleware,\n")
	b.WriteString("  InvokeContext,\n")
	b.WriteString("};\n")
	b.WriteString("export type {\n")
	if runtime != RuntimeEffect {
		b.WriteString("  TaggedError,\n")
	}
	if len(domainErrors) > 0 {
		b.WriteString("  ForstError,\n")
	}
	b.WriteString(`} from "./errors.js";` + "\n")
	b.WriteString("export {\n")
	for _, name := range RootReexportedDomainErrorNames(domainErrors) {
		fmt.Fprintf(&b, "  %s,\n", name)
	}
	b.WriteString(`} from "./errors.js";` + "\n")
	b.WriteString(`export type * from "./types.js";` + "\n")
	return b.String()
}

// EmitTypesDTS returns dist/types.d.ts from pre-rendered shape declarations.
func EmitTypesDTS(shapes []string) string {
	var b strings.Builder
	b.WriteString("// Auto-generated types for Forst client\n")
	b.WriteString("// Generated by Forst TypeScript Transformer\n")
	b.WriteString("// Do not edit by hand.\n\n")
	if len(shapes) > 0 {
		b.WriteString("// Type definitions\n")
		b.WriteString(strings.Join(shapes, "\n\n"))
		b.WriteString("\n")
	}
	return b.String()
}
