package transformerts

import (
	"fmt"
	"strings"
)

// ErrorField describes one constructor prop on a tagged invoke failure class.
type ErrorField struct {
	Name     string
	TSType   string
	Optional bool
}

// ErrorClass is one tagged failure class in the generated dist/errors.* module.
type ErrorClass struct {
	Name   string
	Tag    string
	Fields []ErrorField
}

// ErrorCatalog is the single source of truth for EmitErrorsESM and EmitErrorsDTS.
// Class names never end in "Error" (sidecar condition naming).
var ErrorCatalog = []ErrorClass{
	{
		Name: "InvokeRejected",
		Tag:  "InvokeRejected",
		Fields: []ErrorField{
			{Name: "packageName", TSType: "string"},
			{Name: "functionName", TSType: "string"},
			{Name: "serverError", TSType: "string", Optional: true},
		},
	},
	{
		Name: "InvokeHttpFailure",
		Tag:  "InvokeHttpFailure",
		Fields: []ErrorField{
			{Name: "packageName", TSType: "string"},
			{Name: "functionName", TSType: "string"},
			{Name: "status", TSType: "number"},
			{Name: "responseText", TSType: "string"},
		},
	},
	{
		Name: "InvokeTimedOut",
		Tag:  "InvokeTimedOut",
		Fields: []ErrorField{
			{Name: "packageName", TSType: "string"},
			{Name: "functionName", TSType: "string"},
			{Name: "timeoutMs", TSType: "number", Optional: true},
		},
	},
	{
		Name: "InvokeUnreachable",
		Tag:  "InvokeUnreachable",
		Fields: []ErrorField{
			{Name: "packageName", TSType: "string"},
			{Name: "functionName", TSType: "string"},
			{Name: "baseUrl", TSType: "string"},
		},
	},
	{
		Name: "InvokeBaseUrlMissing",
		Tag:  "InvokeBaseUrlMissing",
		Fields: []ErrorField{
			{Name: "envVar", TSType: "string"},
			{Name: "nodeEnv", TSType: "string"},
		},
	},
	{
		Name: "InvokeStreamAborted",
		Tag:  "InvokeStreamAborted",
		Fields: []ErrorField{
			{Name: "packageName", TSType: "string"},
			{Name: "functionName", TSType: "string"},
			{Name: "rowIndex", TSType: "number"},
		},
	},
	{
		Name: "ContractVersionMismatch",
		Tag:  "ContractVersionMismatch",
		Fields: []ErrorField{
			{Name: "expectedContractVersion", TSType: "string"},
			{Name: "serverContractVersion", TSType: "string"},
		},
	},
}

// ErrorClassNames returns every class name from ErrorCatalog in catalog order.
func ErrorClassNames() []string {
	names := make([]string, len(ErrorCatalog))
	for i, c := range ErrorCatalog {
		names[i] = c.Name
	}
	return names
}

// EmitErrorsESM returns dist/errors.js (tagged failures, no Effect dependency).
func EmitErrorsESM() string {
	var b strings.Builder
	b.WriteString(`// Auto-generated Forst invoke errors.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.
// Tagged Error shape matches Effect Data.TaggedError without an Effect dependency.

`)
	b.WriteString(`const tagged = (tag) =>
  class extends Error {
    constructor(props) {
      super(props?.message ?? tag);
      Object.assign(this, props);
      Object.defineProperty(this, "_tag", {
        value: tag,
        enumerable: true,
        writable: false,
      });
      this.name = tag;
      Object.setPrototypeOf(this, new.target.prototype);
      if (Error.captureStackTrace) Error.captureStackTrace(this, new.target);
    }
  };

`)
	for _, c := range ErrorCatalog {
		fmt.Fprintf(&b, "export class %s extends tagged(%q) {}\n", c.Name, c.Tag)
	}
	b.WriteString("\n")
	b.WriteString("const INVOKE_FAILURE_TAGS = new Set([\n")
	for _, c := range ErrorCatalog {
		fmt.Fprintf(&b, "  %q,\n", c.Tag)
	}
	b.WriteString("]);\n\n")
	b.WriteString("export const isInvokeFailure = (u) =>\n")
	b.WriteString("  u instanceof Error && INVOKE_FAILURE_TAGS.has(u._tag);\n")
	return b.String()
}

// EmitErrorsDTS returns dist/errors.d.ts.
func EmitErrorsDTS() string {
	var b strings.Builder
	b.WriteString(`// Auto-generated Forst invoke errors.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

`)
	b.WriteString(`export type TaggedError<
  Tag extends string,
  A extends Record<string, unknown> = {}
> = Error & { readonly _tag: Tag } & Readonly<A>;

`)
	for _, c := range ErrorCatalog {
		fmt.Fprintf(&b, "export declare class %s extends Error {\n", c.Name)
		fmt.Fprintf(&b, "  readonly _tag: %q;\n", c.Tag)
		for _, f := range c.Fields {
			opt := ""
			if f.Optional {
				opt = " | undefined"
			}
			fmt.Fprintf(&b, "  readonly %s: %s%s;\n", f.Name, f.TSType, opt)
		}
		b.WriteString("  constructor(props: {\n")
		for _, f := range c.Fields {
			optMark := ""
			if f.Optional {
				optMark = "?"
			}
			fmt.Fprintf(&b, "    readonly %s%s: %s;\n", f.Name, optMark, f.TSType)
		}
		b.WriteString("    readonly message?: string;\n")
		b.WriteString("  });\n")
		b.WriteString("}\n\n")
	}
	b.WriteString("export type InvokeFailure =\n")
	for _, c := range ErrorCatalog {
		fmt.Fprintf(&b, "  | %s\n", c.Name)
	}
	b.WriteString(";\n\n")
	b.WriteString("export declare function isInvokeFailure(u: unknown): u is InvokeFailure;\n")
	return b.String()
}

// errorImportListESM returns a comma-separated import list of all error classes.
func errorImportListESM() string {
	return strings.Join(ErrorClassNames(), ", ")
}
