package transformerts

import (
	"strings"
)

// TypeScriptOutput holds the generated TypeScript code
type TypeScriptOutput struct {
	PackageName string
	// SourceFileStem is the basename of the .ft file without extension (e.g. "api" from "api.ft").
	// It names the generated TypeScript client factory (export const <stem>) and must align with
	// imports like import { stem } from './stem.client'. Runtime RPC package name remains PackageName.
	SourceFileStem string
	Types          []string
	// ExportedTypeNames lists identifiers emitted in Types (e.g. interface names) for import type { … } in *.client.ts.
	ExportedTypeNames []string
	Functions         []FunctionSignature
	ClientCode        []string // Per-package client code
	MainClient        string   // Main client class
	TypesFile         string   // Centralized types file
}

// AddType adds a type definition to the output
func (o *TypeScriptOutput) AddType(tsType string) {
	o.Types = append(o.Types, tsType)
}

// AddExportedTypeName records a type name declared in Types (for import type from './types' in client modules).
func (o *TypeScriptOutput) AddExportedTypeName(name string) {
	if name == "" {
		return
	}
	o.ExportedTypeNames = append(o.ExportedTypeNames, name)
}

// AddFunction adds a function definition to the output
func (o *TypeScriptOutput) AddFunction(sig FunctionSignature) {
	o.Functions = append(o.Functions, sig)
}

// SetPackageName sets the package name
func (o *TypeScriptOutput) SetPackageName(name string) {
	o.PackageName = name
}

// GenerateTypesFile builds and returns the centralized types declaration file from
// Types and Functions (using export on interfaces and export function on signatures).
// It always refreshes o.TypesFile from those slices so callers that only populate
// slices (e.g. dev server aggregation) still get valid output.
func (o *TypeScriptOutput) GenerateTypesFile() string {
	o.TypesFile = formatTypesDeclarationFile(o.Types, o.Functions)
	return o.TypesFile
}

// formatTypesDeclarationFile produces the shared .d.ts text for types + function signatures.
func formatTypesDeclarationFile(types []string, functions []FunctionSignature) string {
	var lines []string

	lines = append(lines, "// Auto-generated types for Forst client")
	lines = append(lines, "// Generated by Forst TypeScript Transformer")
	lines = append(lines, "")

	if len(types) > 0 {
		lines = append(lines, "// Type definitions")
		lines = append(lines, strings.Join(types, "\n\n"))
		lines = append(lines, "")
	}

	if len(functions) > 0 {
		lines = append(lines, "// Function signatures")
		sigs := make([]string, len(functions))
		for i := range functions {
			sigs[i] = functions[i].ToString()
		}
		lines = append(lines, strings.Join(sigs, "\n\n"))
		lines = append(lines, "")
	}

	return strings.Join(lines, "\n")
}

// GenerateClientFile returns the package client file content
func (o *TypeScriptOutput) GenerateClientFile() string {
	return strings.Join(o.ClientCode, "\n")
}

// GenerateMainClient returns the main client file content
func (o *TypeScriptOutput) GenerateMainClient() string {
	return o.MainClient
}
