package transformerts

import (
	"strings"
)

// TypeScriptOutput holds the generated TypeScript code
type TypeScriptOutput struct {
	PackageName string
	// SourceFileStem is the basename of the .ft file without extension (e.g. "api" from "api.ft").
	// It names the generated TypeScript client factory (export const <stem>) and must align with
	// imports like import { stem } from './pkg/stem.js'. Runtime RPC package name remains PackageName.
	SourceFileStem string
	Types          []string
	// ExportedTypeNames lists identifiers emitted in Types (e.g. interface names) for import type { … }.
	ExportedTypeNames []string
	Functions         []FunctionSignature
	// OmittedFunctions lists public functions skipped for unsatisfied Providers (F-17).
	OmittedFunctions []OmittedFunction
	ClientCode       []string // Per-package core module (Promise implementation)
	MainClient       string   // Main client factory (legacy field; root index is built in cmd/forst)
	TypesFile        string   // Centralized types file
}

// AddType adds a type definition to the output
func (o *TypeScriptOutput) AddType(tsType string) {
	o.Types = append(o.Types, tsType)
}

// AddExportedTypeName records a type name declared in Types (for import type from '../types' in client modules).
func (o *TypeScriptOutput) AddExportedTypeName(name string) {
	if name == "" {
		return
	}
	o.ExportedTypeNames = append(o.ExportedTypeNames, name)
}

// AddFunction adds a function definition to the output
func (o *TypeScriptOutput) AddFunction(sig FunctionSignature) {
	o.Functions = append(o.Functions, sig)
}

// SetPackageName sets the package name
func (o *TypeScriptOutput) SetPackageName(name string) {
	o.PackageName = name
}

// GenerateTypesFile builds and returns the centralized types declaration file from
// shape Types only. Function signatures live on package modules (and .d.ts after Phase 3).
// StreamingResult remains when any function needs it (it is a shape, not a signature).
func (o *TypeScriptOutput) GenerateTypesFile() string {
	o.TypesFile = formatTypesDeclarationFile(o.Types, o.Functions)
	return o.TypesFile
}

// formatTypesDeclarationFile produces the shared .d.ts text for shape types only.
func formatTypesDeclarationFile(types []string, functions []FunctionSignature) string {
	var lines []string

	lines = append(lines, "// Auto-generated types for Forst client")
	lines = append(lines, "// Generated by Forst TypeScript Transformer")
	lines = append(lines, "")

	if len(types) > 0 {
		lines = append(lines, "// Type definitions")
		lines = append(lines, strings.Join(types, "\n\n"))
		lines = append(lines, "")
	}

	if functionsNeedStreamingResult(functions) {
		lines = append(lines, "// Streaming")
		lines = append(lines, EmitStreamingResultTypeDeclaration())
		lines = append(lines, "")
	}

	return strings.Join(lines, "\n")
}

// GenerateClientFile returns the package core module content (Promise implementation).
func (o *TypeScriptOutput) GenerateClientFile() string {
	return o.GenerateCoreModule()
}

// GenerateCoreModule returns the Promise implementation under src/core/<pkg>.ts.
func (o *TypeScriptOutput) GenerateCoreModule() string {
	return strings.Join(o.ClientCode, "\n")
}

// GeneratePackageModule returns the public subpath module under src/pkg/<pkg>.ts.
// In Promise mode this re-exports core and the shape types used by the package.
func (o *TypeScriptOutput) GeneratePackageModule() string {
	pkg := o.PackageName
	if pkg == "" {
		pkg = o.SourceFileStem
	}
	var b strings.Builder
	b.WriteString("// Auto-generated public module for " + pkg + " package\n")
	b.WriteString("// Generated by Forst TypeScript Transformer\n")
	b.WriteString("// Promise mode: re-export core. Effect mode (Phase 6) wraps the same core.\n\n")
	b.WriteString("export * from \"../core/" + pkg + ".js\";\n")
	names := sortDedupeStrings(o.ExportedTypeNames)
	if len(names) > 0 {
		b.WriteString("export type { " + strings.Join(names, ", ") + " } from \"../types.js\";\n")
	}
	return b.String()
}

// GenerateMainClient returns the main client file content
func (o *TypeScriptOutput) GenerateMainClient() string {
	return o.MainClient
}
