package transformerts

import (
	"fmt"
	"strings"
	"unicode"
	"unicode/utf8"
)

// EmitTestingESM returns dist/testing.js (AsyncLocalStorage test scope + createTestForstClient + startForstTestServer).
func EmitTestingESM(modules []ModuleEmit) string {
	mods := sortModulesByPackage(modules)
	var b strings.Builder
	b.WriteString(`// Auto-generated Forst test scope.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

import { ForstTestServerFailed, InvokeRejected } from "./errors.js";
import {
  configureDefaultInvokeClient,
  resetDefaultInvokeClientForTest,
  setActiveTestTransportResolver,
} from "./transport.js";

export { ForstTestServerFailed, InvokeRejected };
`)
	for _, m := range mods {
		pkg := m.PackageName
		if pkg == "" {
			continue
		}
		fmt.Fprintf(&b, "import { %s } from \"./pkg/%s.js\";\n", pkg, pkg)
	}
	b.WriteString("\n")
	b.WriteString(testingRuntimeESM)
	b.WriteString("\n")
	b.WriteString("export function createTestForstClient(handlers) {\n")
	b.WriteString("  const transport = createScopeTransport({ packages: handlers ?? {} }, undefined);\n")
	b.WriteString("  return {\n")
	for _, m := range mods {
		pkg := m.PackageName
		if pkg == "" {
			continue
		}
		fmt.Fprintf(&b, "    %s: %s(transport),\n", pkg, pkg)
	}
	b.WriteString("  };\n")
	b.WriteString("}\n\n")
	emitTestServerStartHelperESM(&b)
	b.WriteString("\n")
	b.WriteString(`export async function startForstTestServer(options) {
  const handle = await startInvokeServerHandle(options);
  resetDefaultInvokeClientForTest();
  configureDefaultInvokeClient({ baseUrl: handle.baseUrl });
  const stop = async () => {
    try {
      await handle.stop();
    } finally {
      resetDefaultInvokeClientForTest();
    }
  };
  return {
    baseUrl: handle.baseUrl,
    port: handle.port,
    pid: handle.pid,
    connection: handle.connection,
    stop,
    [Symbol.asyncDispose]: stop,
  };
}
`)
	return b.String()
}

// EmitTestingDTS returns dist/testing.d.ts with per-package handler maps under packages.
func EmitTestingDTS(modules []ModuleEmit) string {
	mods := sortModulesByPackage(modules)
	typeImports := collectTestingTypeImports(mods)
	var b strings.Builder
	b.WriteString(`// Auto-generated Forst test scope.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

import type {
  ForstInvokeClient,
  InvokeCallOptions,
} from "./transport.js";
import { ForstTestServerFailed, InvokeRejected } from "./errors.js";

export { ForstTestServerFailed, InvokeRejected };
`)
	if len(typeImports) > 0 {
		fmt.Fprintf(&b, "import type { %s } from \"./types.js\";\n", strings.Join(typeImports, ", "))
	}
	b.WriteString("\n")

	for _, m := range mods {
		pkg := m.PackageName
		if pkg == "" {
			continue
		}
		fmt.Fprintf(&b, "export type %s = {\n", handlersTypeName(pkg))
		for _, fn := range m.Functions {
			params := emitParamListDTS(fn.Parameters, true)
			fmt.Fprintf(&b, "  %s: (%s) => Promise<%s>;\n", fn.Name, params, fn.ReturnType)
			if fn.StreamingRowType != "" {
				fmt.Fprintf(&b,
					"  %sStream: (%s) => AsyncGenerator<import(\"./transport.js\").StreamingResult & { data?: %s }, void, undefined>;\n",
					fn.Name, params, fn.StreamingRowType,
				)
			}
		}
		b.WriteString("};\n\n")
	}

	b.WriteString("export interface ForstTestOverrides {\n")
	b.WriteString("  /** Replace whole packages or single functions. Both levels use this map. */\n")
	b.WriteString("  packages?: {\n")
	for _, m := range mods {
		pkg := m.PackageName
		if pkg == "" {
			continue
		}
		fmt.Fprintf(&b, "    %s?: Partial<%s>;\n", pkg, handlersTypeName(pkg))
	}
	b.WriteString("  };\n")
	b.WriteString("  /** Replace the raw invoke calls, to assert on the wire or simulate failures. */\n")
	b.WriteString("  transport?: Partial<ForstInvokeClient>;\n")
	b.WriteString("}\n\n")

	b.WriteString("export declare function withForstTestScope<T>(\n")
	b.WriteString("  overrides: ForstTestOverrides,\n")
	b.WriteString("  run: () => Promise<T>\n")
	b.WriteString("): Promise<T>;\n\n")

	b.WriteString("export declare function createTestForstClient(\n")
	b.WriteString("  handlers?: ForstTestOverrides[\"packages\"]\n")
	b.WriteString("): {\n")
	for _, m := range mods {
		pkg := m.PackageName
		if pkg == "" {
			continue
		}
		fmt.Fprintf(&b, "  readonly %s: ReturnType<typeof import(\"./pkg/%s.js\").%s>;\n", pkg, pkg, pkg)
	}
	b.WriteString("};\n\n")
	emitForstTestServerOptionsDTS(&b)
	emitForstTestServerHandleDTS(&b)
	b.WriteString("export declare function startForstTestServer(\n")
	b.WriteString("  options?: ForstTestServerOptions\n")
	b.WriteString("): Promise<ForstTestServer>;\n")
	return b.String()
}

func handlersTypeName(pkg string) string {
	if pkg == "" {
		return "Handlers"
	}
	r, size := utf8.DecodeRuneInString(pkg)
	if r == utf8.RuneError && size == 0 {
		return "Handlers"
	}
	return string(unicode.ToUpper(r)) + pkg[size:] + "Handlers"
}

func sortModulesByPackage(modules []ModuleEmit) []ModuleEmit {
	out := append([]ModuleEmit(nil), modules...)
	// Insertion sort keeps the file free of sort import for this tiny list.
	for i := 1; i < len(out); i++ {
		j := i
		for j > 0 && out[j-1].PackageName > out[j].PackageName {
			out[j-1], out[j] = out[j], out[j-1]
			j--
		}
	}
	return out
}

func collectTestingTypeImports(modules []ModuleEmit) []string {
	var names []string
	for _, m := range modules {
		names = append(names, m.TypeImports...)
		for _, fn := range m.Functions {
			for _, p := range fn.Parameters {
				if p.Type != "" {
					names = append(names, p.Type)
				}
			}
			if fn.ReturnType != "" {
				names = append(names, fn.ReturnType)
			}
			if fn.StreamingRowType != "" {
				names = append(names, fn.StreamingRowType)
			}
		}
	}
	return filterTypeScriptTypeNames(sortDedupeStrings(names))
}

// filterTypeScriptTypeNames drops builtins and inline types that are not importable from types.js.
func filterTypeScriptTypeNames(names []string) []string {
	out := make([]string, 0, len(names))
	for _, n := range names {
		if !isImportableGeneratedTypeName(n) {
			continue
		}
		out = append(out, n)
	}
	return out
}

func isImportableGeneratedTypeName(name string) bool {
	if name == "" {
		return false
	}
	switch name {
	case "string", "number", "boolean", "void", "undefined", "null", "any", "unknown",
		"object", "never", "bigint", "symbol", "InvokeCallOptions", "ForstInvokeClient",
		"StreamingResult":
		return false
	}
	if strings.ContainsAny(name, "|&<>{}[]()\"'` ") {
		return false
	}
	if strings.HasPrefix(name, "Promise") || strings.HasPrefix(name, "Async") {
		return false
	}
	r, _ := utf8.DecodeRuneInString(name)
	return unicode.IsUpper(r)
}

// testingRuntimeESM is the shared AsyncLocalStorage scope + transport dispatch.
const testingRuntimeESM = `let AsyncLocalStorageCtor;
try {
  // process.getBuiltinModule avoids a node: import (keeps emit relative-import clean).
  const hooks =
    typeof process !== "undefined" &&
    typeof process.getBuiltinModule === "function"
      ? process.getBuiltinModule("async_hooks")
      : undefined;
  AsyncLocalStorageCtor = hooks?.AsyncLocalStorage;
} catch {
  AsyncLocalStorageCtor = undefined;
}

const scopeStorage = AsyncLocalStorageCtor ? new AsyncLocalStorageCtor() : undefined;
let fallbackScope;

function getActiveScope() {
  if (scopeStorage) {
    return scopeStorage.getStore();
  }
  return fallbackScope;
}

function mergePackageMaps(parent, child) {
  const out = { ...(parent ?? {}) };
  for (const [pkg, handlers] of Object.entries(child ?? {})) {
    out[pkg] = { ...(out[pkg] ?? {}), ...(handlers ?? {}) };
  }
  return out;
}

function mergeOverrides(parent, child) {
  const parentTransport = parent?.transport ?? {};
  const childTransport = child?.transport ?? {};
  return {
    packages: mergePackageMaps(parent?.packages, child?.packages),
    transport: {
      invokeFunction:
        childTransport.invokeFunction ?? parentTransport.invokeFunction,
      invokeStream: childTransport.invokeStream ?? parentTransport.invokeStream,
    },
  };
}

function createScopeTransport(scope, parentTransport) {
  return {
    async invokeFunction(packageName, functionName, args = [], options) {
      if (typeof scope.transport?.invokeFunction === "function") {
        return scope.transport.invokeFunction(
          packageName,
          functionName,
          args,
          options
        );
      }
      const handler = scope.packages?.[packageName]?.[functionName];
      if (typeof handler === "function") {
        const result = await handler(...args, options);
        return { success: true, result };
      }
      if (parentTransport && typeof parentTransport.invokeFunction === "function") {
        return parentTransport.invokeFunction(
          packageName,
          functionName,
          args,
          options
        );
      }
      throw new InvokeRejected({
        packageName,
        functionName,
        serverError:
          "no test handler for " + packageName + "." + functionName,
      });
    },
    async *invokeStream(packageName, functionName, args = [], options) {
      if (typeof scope.transport?.invokeStream === "function") {
        yield* scope.transport.invokeStream(
          packageName,
          functionName,
          args,
          options
        );
        return;
      }
      const handler = scope.packages?.[packageName]?.[functionName + "Stream"];
      if (typeof handler === "function") {
        yield* handler(...args, options);
        return;
      }
      if (parentTransport && typeof parentTransport.invokeStream === "function") {
        yield* parentTransport.invokeStream(
          packageName,
          functionName,
          args,
          options
        );
        return;
      }
      throw new InvokeRejected({
        packageName,
        functionName,
        serverError:
          "no test handler for " + packageName + "." + functionName + "Stream",
      });
    },
  };
}

setActiveTestTransportResolver(() => getActiveScope()?.transport);

/**
 * Installs package/function/transport overrides for the duration of run.
 * Nested scopes merge; the innermost override wins. Restores in finally.
 */
export async function withForstTestScope(overrides, run) {
  const parent = getActiveScope();
  const merged = mergeOverrides(parent?.overrides, overrides ?? {});
  const parentTransport = parent?.transport;
  const transport = createScopeTransport(merged, parentTransport);
  const store = { overrides: merged, transport };

  if (scopeStorage) {
    return scopeStorage.run(store, run);
  }

  const previous = fallbackScope;
  fallbackScope = store;
  try {
    return await run();
  } finally {
    fallbackScope = previous;
  }
}
`
