package transformerts

import (
	"strings"

	"forst/internal/invokeserver"
)

// DefaultInvokePort is the embedded invoke listen port used when EmitTransport*
// is called with an empty port. Matches ftconfig.DefaultEmbeddedInvokePort.
const DefaultInvokePort = "6321"

// TransportModuleSpecifier is the relative ESM import path for the inlined transport
// module written next to generated clients. The .js extension is required for Node
// ESM resolution. The .js extension is required for Node when importing the inlined transport module.
const TransportModuleSpecifier = "./transport.js"

// EmitStreamingResultTypeDeclaration returns the StreamingResult interface copied into
// generated types.d.ts when any exported function uses streaming. Kept in sync with
// the interface inside EmitTransportDTS / EmitTransportTypeScript.
func EmitStreamingResultTypeDeclaration() string {
	return `/** One NDJSON line from a streaming POST /invoke response. */
export interface StreamingResult {
  data: any;
  status: string;
  error?: string;
}`
}

// functionsNeedStreamingResult reports whether types.d.ts must include StreamingResult.
func functionsNeedStreamingResult(functions []FunctionSignature) bool {
	for i := range functions {
		if functions[i].StreamingRowType != "" {
			return true
		}
	}
	return false
}

// transportInvokePortPlaceholder is substituted with the resolved invoke port.
const transportInvokePortPlaceholder = "{{INVOKE_PORT}}"

// transportContractVersionPlaceholder is substituted with invokeserver.HTTPContractVersion.
const transportContractVersionPlaceholder = "{{CONTRACT_VERSION}}"

func resolveTransportInvokePort(invokePort string) string {
	if invokePort == "" {
		return DefaultInvokePort
	}
	return invokePort
}

func substituteInvokePort(src, invokePort string) string {
	return strings.ReplaceAll(src, transportInvokePortPlaceholder, resolveTransportInvokePort(invokePort))
}

func substituteContractVersion(src string) string {
	return strings.ReplaceAll(src, transportContractVersionPlaceholder, invokeserver.HTTPContractVersion)
}

func substituteTransportPlaceholders(src, invokePort string) string {
	return substituteContractVersion(substituteInvokePort(src, invokePort))
}

func transportFileHeader(invokePort string, runtime ClientRuntime) string {
	header := substituteInvokePort(`// Auto-generated Forst invoke transport (connect-only).
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.
//
// Connect to embedded invoke: FORST_BASE_URL=http://127.0.0.1:{{INVOKE_PORT}}
// Env overrides (first wins): FORST_INVOKE_URL, FORST_BASE_URL, FORST_DEV_URL
// Production (NODE_ENV=production): FORST_BASE_URL (or config) is required; never spawns.

`, invokePort)
	if runtime == RuntimeEffect {
		header = strings.Replace(header, "// Do not edit by hand.\n", "// Effect mode. Do not edit by hand.\n", 1)
	}
	return header
}

func transportErrorsImport(runtime ClientRuntime) string {
	pkg := errorsPackageImport(runtime)
	return "import {\n  " + strings.Join(ErrorClassNames(), ",\n  ") + ",\n} from \"" + pkg + "\";\nimport { decodeDomainError } from \"" + ErrorsModuleSpecifier + "\";\n\n"
}

// EmitTransportESM returns dist/transport.js (connect-only HTTP invoke + NDJSON stream).
func EmitTransportESM(invokePort string, runtime ClientRuntime) string {
	return substituteTransportPlaceholders(
		transportFileHeader(invokePort, runtime)+
			transportErrorsImport(runtime)+
			transportRuntimeESM,
		invokePort,
	)
}

// EmitTransportDTS returns dist/transport.d.ts for the inlined transport module.
func EmitTransportDTS() string {
	return `// Auto-generated Forst invoke transport (connect-only).
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

` + transportTypeDeclarationsDTS
}

// EmitTransportTypeScript returns the TypeScript source for the generated package's
// inlined connect-only HTTP invoke transport (src/transport.ts during development).
//
// Built from the same runtime body as EmitTransportESM plus the type surface so the
// checked-in .ts source and the generated .js/.d.ts pair cannot drift. The shared runtime is plain
// JS, so the file starts with @ts-nocheck.
//
// invokePort is the default listen port embedded in the fallback base URL
// (http://127.0.0.1:<port>). Pass cfg.Server.EffectiveInvokePort() from generate.
// An empty invokePort uses DefaultInvokePort.
func EmitTransportTypeScript(invokePort string, runtime ClientRuntime) string {
	return "// @ts-nocheck\n" +
		substituteTransportPlaceholders(
			transportFileHeader(invokePort, runtime)+
				transportErrorsImport(runtime)+
				transportTypeDeclarationsTS+"\n"+
				transportRuntimeESM,
			invokePort,
		)
}

// transportTypeDeclarationsTS is the type surface inlined into EmitTransportTypeScript.
// Interfaces keep generics so existing consumers and tests see invokeFunction<T>.
const transportTypeDeclarationsTS = `/** One NDJSON line from a streaming POST /invoke response. */
export interface StreamingResult {
  data: any;
  status: string;
  error?: string;
}

/** Successful non-streaming POST /invoke envelope after HTTP 2xx. */
export interface InvokeSuccess<T = unknown> {
  success: true;
  result: T;
  output?: string;
  error?: string;
}

/** Per-call options accepted by invokeFunction / invokeStream. */
export interface InvokeCallOptions {
  signal?: AbortSignal;
  timeoutMs?: number;
  retries?: number;
  /** Per-call HTTP headers merged over config.headers. */
  headers?: Record<string, string>;
  /** Internal. Used by Effect mode and the test scope to inject a transport. */
  transport?: ForstInvokeClient;
}

/** Context passed to observability middleware around each invoke. */
export interface InvokeContext {
  packageName: string;
  functionName: string;
  attempt: number;
  startedAt: number;
}

/** Observability hooks for createForstClient / configureDefaultInvokeClient. */
export interface ForstInvokeMiddleware {
  onStart?(ctx: InvokeContext): void | Promise<void>;
  onSuccess?(ctx: InvokeContext, result: unknown): void | Promise<void>;
  /** error is InvokeFailure from errors.js when thrown by the transport. */
  onFailure?(ctx: InvokeContext, error: unknown): void | Promise<void>;
}

/** Connect-only transport configuration. */
export interface ForstInvokeClientConfig {
  baseUrl?: string;
  /** Alias accepted for parity with older clients. */
  devServerUrl?: string;
  timeout?: number;
  retries?: number;
  /** Opt-in spawn of forst dev (ignored when NODE_ENV=production). Off by default. */
  allowSpawn?: boolean;
  /** "dev" opts into spawn path (same as allowSpawn). Off by default. */
  transport?: "http" | "dev";
  /** Injectable fetch for tests. */
  fetchFn?: typeof fetch;
  /** Default HTTP headers merged into every invoke (for example Authorization). */
  headers?: Record<string, string>;
  /** Observability middleware chain (request start / success / failure). */
  middleware?: ForstInvokeMiddleware[];
}

/**
 * Minimal invoke surface used by generated clients.
 * HTTP connect by default. Never spawns when NODE_ENV=production.
 */
export interface ForstInvokeClient {
  invokeFunction<T>(
    packageName: string,
    functionName: string,
    args?: unknown[],
    options?: InvokeCallOptions
  ): Promise<InvokeSuccess<T>>;
  invokeStream<T = unknown>(
    packageName: string,
    functionName: string,
    args?: unknown[],
    options?: InvokeCallOptions
  ): AsyncGenerator<StreamingResult & { data?: T }, void, undefined>;
}
`

// transportTypeDeclarationsDTS is the .d.ts surface for EmitTransportDTS.
const transportTypeDeclarationsDTS = `/** One NDJSON line from a streaming POST /invoke response. */
export interface StreamingResult {
  data: any;
  status: string;
  error?: string;
}

/** Successful non-streaming POST /invoke envelope after HTTP 2xx. */
export interface InvokeSuccess<T = unknown> {
  success: true;
  result: T;
  output?: string;
  error?: string;
}

/** Per-call options accepted by invokeFunction / invokeStream. */
export interface InvokeCallOptions {
  signal?: AbortSignal;
  timeoutMs?: number;
  retries?: number;
  /** Per-call HTTP headers merged over config.headers. */
  headers?: Record<string, string>;
  /** Internal. Used by Effect mode and the test scope to inject a transport. */
  transport?: ForstInvokeClient;
}

/** Context passed to observability middleware around each invoke. */
export interface InvokeContext {
  packageName: string;
  functionName: string;
  attempt: number;
  startedAt: number;
}

/** Observability hooks for createForstClient / configureDefaultInvokeClient. */
export interface ForstInvokeMiddleware {
  onStart?(ctx: InvokeContext): void | Promise<void>;
  onSuccess?(ctx: InvokeContext, result: unknown): void | Promise<void>;
  /** error is InvokeFailure from errors.js when thrown by the transport. */
  onFailure?(ctx: InvokeContext, error: unknown): void | Promise<void>;
}

/** Connect-only transport configuration. */
export interface ForstInvokeClientConfig {
  baseUrl?: string;
  /** Alias accepted for parity with older clients. */
  devServerUrl?: string;
  timeout?: number;
  retries?: number;
  /** Opt-in spawn of forst dev (ignored when NODE_ENV=production). Off by default. */
  allowSpawn?: boolean;
  /** "dev" opts into spawn path (same as allowSpawn). Off by default. */
  transport?: "http" | "dev";
  /** Injectable fetch for tests. */
  fetchFn?: typeof fetch;
  /** Default HTTP headers merged into every invoke (for example Authorization). */
  headers?: Record<string, string>;
  /** Observability middleware chain (request start / success / failure). */
  middleware?: ForstInvokeMiddleware[];
}

/**
 * Minimal invoke surface used by generated clients.
 * HTTP connect by default. Never spawns when NODE_ENV=production.
 */
export interface ForstInvokeClient {
  invokeFunction<T>(
    packageName: string,
    functionName: string,
    args?: unknown[],
    options?: InvokeCallOptions
  ): Promise<InvokeSuccess<T>>;
  invokeStream<T = unknown>(
    packageName: string,
    functionName: string,
    args?: unknown[],
    options?: InvokeCallOptions
  ): AsyncGenerator<StreamingResult & { data?: T }, void, undefined>;
}

/** Instantiates a connect-only HTTP invoke client. Never spawns in production. */
export declare function createInvokeClient(
  config?: ForstInvokeClientConfig
): ForstInvokeClient;

/** Lazy process-wide default client for generated call sites. */
export declare function getDefaultInvokeClient(): ForstInvokeClient;

/**
 * Merge config into the default singleton used by flat package exports.
 * Resets the cached client so the next call picks up middleware and base URL.
 */
export declare function configureDefaultInvokeClient(
  config: ForstInvokeClientConfig
): void;

/** Clears the default singleton so tests can swap transport config between cases. */
export declare function resetDefaultInvokeClientForTest(): void;

/**
 * Internal. The testing subpath registers a resolver so flat exports honour
 * withForstTestScope without mutating module-level override maps.
 */
export declare function setActiveTestTransportResolver(
  resolve: (() => ForstInvokeClient | undefined) | undefined
): void;
`

// transportRuntimeESM is the shared connect-only HTTP + NDJSON implementation.
// Used by EmitTransportESM and EmitTransportTypeScript (valid as both .js and .ts).
// Placeholders: {{INVOKE_PORT}}
// Throws tagged failures from ./errors.js. Never bare Error for invoke failures.
const transportRuntimeESM = `const defaultInvokeBaseUrl = "http://127.0.0.1:{{INVOKE_PORT}}";
const EXPECTED_CONTRACT_VERSION = "{{CONTRACT_VERSION}}";

function mergeHeaders(config, options) {
  const out = { "Content-Type": "application/json" };
  const cfgHeaders = config?.headers;
  if (cfgHeaders) {
    for (const [key, value] of Object.entries(cfgHeaders)) {
      if (value !== undefined && value !== null) {
        out[key] = String(value);
      }
    }
  }
  const callHeaders = options?.headers;
  if (callHeaders) {
    for (const [key, value] of Object.entries(callHeaders)) {
      if (value !== undefined && value !== null) {
        out[key] = String(value);
      }
    }
  }
  return out;
}

function checkContractVersion(response, packageName, functionName) {
  const got = response.headers.get("X-Forst-Contract-Version");
  if (got && got !== EXPECTED_CONTRACT_VERSION) {
    throw new ContractVersionMismatch({
      expectedContractVersion: EXPECTED_CONTRACT_VERSION,
      serverContractVersion: got,
      message:
        "invoke contract version mismatch for " +
        packageName +
        "." +
        functionName +
        ": expected " +
        EXPECTED_CONTRACT_VERSION +
        ", got " +
        got,
    });
  }
}

async function retryDelayMs(attempt) {
  const base = 100;
  const cap = 2000;
  const exp = Math.min(cap, base * Math.pow(2, attempt));
  const jitter = Math.floor(Math.random() * exp * 0.25);
  await new Promise((resolve) => setTimeout(resolve, exp + jitter));
}

function resolveEnvBaseUrl() {
  const proc = typeof process !== "undefined" ? process : undefined;
  const env = proc?.env;
  if (!env) {
    return undefined;
  }
  return env.FORST_INVOKE_URL ?? env.FORST_BASE_URL ?? env.FORST_DEV_URL;
}

function resolveConfiguredBaseUrl(config) {
  const raw = config?.baseUrl ?? config?.devServerUrl ?? resolveEnvBaseUrl();
  if (!raw) {
    return undefined;
  }
  return String(raw).replace(/\/$/, "");
}

function resolveBaseUrl(config) {
  return resolveConfiguredBaseUrl(config) ?? defaultInvokeBaseUrl.replace(/\/$/, "");
}

function nodeEnv() {
  const proc = typeof process !== "undefined" ? process : undefined;
  return proc?.env?.NODE_ENV;
}

/**
 * Resolve transport mode. Spawn is opt-in and forbidden in production (F-12).
 * Full forst dev spawn is deferred; "dev" still connects over HTTP for now.
 */
function resolveTransportMode(config) {
  const env = nodeEnv();
  const proc = typeof process !== "undefined" ? process : undefined;
  if (proc?.env?.FORST_SKIP_SPAWN === "1") {
    if (env === "production" && !resolveConfiguredBaseUrl(config)) {
      throw new InvokeBaseUrlMissing({
        envVar: "FORST_BASE_URL",
        nodeEnv: "production",
        message: "FORST_BASE_URL is required when NODE_ENV=production",
      });
    }
    return "http";
  }
  if (env === "production") {
    if (!resolveConfiguredBaseUrl(config)) {
      throw new InvokeBaseUrlMissing({
        envVar: "FORST_BASE_URL",
        nodeEnv: "production",
        message: "FORST_BASE_URL is required when NODE_ENV=production",
      });
    }
    // Never spawn in production, even if allowSpawn / transport: "dev" is set.
    return "http";
  }
  if (config?.transport === "dev" || config?.allowSpawn === true) {
    return "dev";
  }
  return "http";
}

function combineSignals(timeoutMs, signal) {
  if (timeoutMs !== undefined && timeoutMs > 0) {
    const timeoutSignal = AbortSignal.timeout(timeoutMs);
    if (!signal) {
      return timeoutSignal;
    }
    if (typeof AbortSignal.any === "function") {
      return AbortSignal.any([signal, timeoutSignal]);
    }
    return timeoutSignal;
  }
  return signal;
}

function isAbortError(err) {
  if (err === null || typeof err !== "object") {
    return false;
  }
  const name = err.name;
  return name === "AbortError" || name === "TimeoutError";
}

function shouldRetryInvokeFailure(err) {
  if (!err || typeof err !== "object") {
    return false;
  }
  const tag = err._tag;
  return tag === "InvokeUnreachable" || tag === "InvokeHttpFailure";
}

class HttpInvokeClient {
  constructor(config) {
    resolveTransportMode(config);
    this.baseUrl = resolveBaseUrl(config);
    this.timeoutMs = config?.timeout ?? 30_000;
    this.retries = config?.retries ?? 0;
    this.fetchFn = config?.fetchFn ?? fetch.bind(globalThis);
    this.middleware = config?.middleware ?? [];
    this.headers = config?.headers ?? {};
  }

  async runMiddleware(hook, ctx, arg) {
    for (const mw of this.middleware) {
      const fn = mw?.[hook];
      if (typeof fn === "function") {
        await fn(ctx, arg);
      }
    }
  }

  async invokeFunction(packageName, functionName, args = [], options) {
    const retries = options?.retries ?? this.retries;
    let attempt = 0;
    const startedAt = Date.now();
    for (;;) {
      const ctx = {
        packageName,
        functionName,
        attempt: attempt + 1,
        startedAt,
      };
      await this.runMiddleware("onStart", ctx);
      try {
        const result = await this.invokeFunctionOnce(
          packageName,
          functionName,
          args,
          options
        );
        await this.runMiddleware("onSuccess", ctx, result);
        return result;
      } catch (err) {
        if (attempt >= retries || !shouldRetryInvokeFailure(err)) {
          await this.runMiddleware("onFailure", ctx, err);
          throw err;
        }
        attempt += 1;
        await retryDelayMs(attempt);
      }
    }
  }

  async invokeFunctionOnce(packageName, functionName, args = [], options) {
    const timeoutMs = options?.timeoutMs ?? this.timeoutMs;
    const signal = combineSignals(timeoutMs, options?.signal);
    const body = JSON.stringify({
      package: packageName,
      function: functionName,
      args,
    });
    let response;
    try {
      response = await this.fetchFn(this.baseUrl + "/invoke", {
        method: "POST",
        headers: mergeHeaders({ headers: this.headers }, options),
        body,
        signal,
      });
    } catch (err) {
      if (isAbortError(err)) {
        throw new InvokeTimedOut({
          packageName,
          functionName,
          timeoutMs,
          message:
            "invoke timed out for " +
            packageName +
            "." +
            functionName,
        });
      }
      throw new InvokeUnreachable({
        packageName,
        functionName,
        baseUrl: this.baseUrl,
        message:
          "invoke unreachable " +
          packageName +
          "." +
          functionName +
          " at " +
          this.baseUrl +
          ": " +
          String(err),
      });
    }
    const responseText = await response.text();
    checkContractVersion(response, packageName, functionName);
    if (!response.ok) {
      throw new InvokeHttpFailure({
        packageName,
        functionName,
        status: response.status,
        responseText,
        message:
          "invoke HTTP " +
          String(response.status) +
          " for " +
          packageName +
          "." +
          functionName +
          ": " +
          responseText,
      });
    }
    let envelope;
    try {
      envelope = JSON.parse(responseText);
    } catch {
      throw new InvokeRejected({
        packageName,
        functionName,
        serverError: "invoke response is not JSON: " + responseText,
        message:
          "invoke response is not JSON for " +
          packageName +
          "." +
          functionName,
      });
    }
    if (!envelope.success) {
      if (envelope.errorValue) {
        throw decodeDomainError(envelope.errorValue, {
          packageName,
          functionName,
          serverError: envelope.error,
        });
      }
      throw new InvokeRejected({
        packageName,
        functionName,
        serverError: envelope.error,
        message:
          envelope.error ??
          "invoke rejected for " + packageName + "." + functionName,
      });
    }
    if (envelope.result === undefined) {
      throw new InvokeRejected({
        packageName,
        functionName,
        serverError: envelope.error,
        message:
          envelope.error ??
          "invoke response missing result for " +
            packageName +
            "." +
            functionName,
      });
    }
    return {
      success: true,
      result: envelope.result,
      output: envelope.output,
      error: envelope.error,
    };
  }

  async *invokeStream(packageName, functionName, args = [], options) {
    const ctx = {
      packageName,
      functionName,
      attempt: 1,
      startedAt: Date.now(),
    };
    await this.runMiddleware("onStart", ctx);
    try {
      yield* this.invokeStreamBody(packageName, functionName, args, options);
      await this.runMiddleware("onSuccess", ctx, undefined);
    } catch (err) {
      await this.runMiddleware("onFailure", ctx, err);
      throw err;
    }
  }

  async *invokeStreamBody(packageName, functionName, args = [], options) {
    const timeoutMs = options?.timeoutMs ?? this.timeoutMs;
    const signal = combineSignals(timeoutMs, options?.signal);
    const body = JSON.stringify({
      package: packageName,
      function: functionName,
      args,
      streaming: true,
    });
    let response;
    try {
      response = await this.fetchFn(this.baseUrl + "/invoke", {
        method: "POST",
        headers: mergeHeaders({ headers: this.headers }, options),
        body,
        signal,
      });
    } catch (err) {
      if (isAbortError(err)) {
        return;
      }
      throw new InvokeUnreachable({
        packageName,
        functionName,
        baseUrl: this.baseUrl,
        message:
          "invoke stream unreachable " +
          packageName +
          "." +
          functionName +
          " at " +
          this.baseUrl +
          ": " +
          String(err),
      });
    }
    if (!response.ok) {
      const responseText = await response.text();
      throw new InvokeHttpFailure({
        packageName,
        functionName,
        status: response.status,
        responseText,
        message:
          "invoke stream HTTP " +
          String(response.status) +
          " for " +
          packageName +
          "." +
          functionName +
          ": " +
          responseText,
      });
    }
    checkContractVersion(response, packageName, functionName);
    if (!response.body) {
      throw new InvokeStreamAborted({
        packageName,
        functionName,
        rowIndex: 0,
        message:
          "invoke stream response missing body for " +
          packageName +
          "." +
          functionName,
      });
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    let rowIndex = 0;

    const abortAndEnd = () => {
      if (signal?.aborted) {
        try {
          void reader.cancel();
        } catch {
          // ignore cancel errors
        }
        return true;
      }
      return false;
    };

    try {
      while (true) {
        if (abortAndEnd()) {
          return;
        }
        let done = false;
        let value;
        try {
          const chunk = await reader.read();
          done = chunk.done;
          value = chunk.value;
        } catch (err) {
          if (isAbortError(err) || signal?.aborted) {
            return;
          }
          throw err;
        }
        if (done) {
          break;
        }
        buffer += decoder.decode(value, { stream: true });
        let newline = buffer.indexOf("\n");
        while (newline >= 0) {
          const line = buffer.slice(0, newline).replace(/\r$/, "");
          buffer = buffer.slice(newline + 1);
          newline = buffer.indexOf("\n");
          if (line.trim() === "") {
            continue;
          }
          let parsed;
          try {
            parsed = JSON.parse(line);
          } catch {
            throw new InvokeStreamAborted({
              packageName,
              functionName,
              rowIndex,
              message:
                "invoke stream row failed to parse for " +
                packageName +
                "." +
                functionName +
                " at row " +
                String(rowIndex),
            });
          }
          rowIndex += 1;
          yield parsed;
          if (abortAndEnd()) {
            return;
          }
        }
      }
      buffer += decoder.decode();
      const trailing = buffer.replace(/\r$/, "");
      if (trailing.trim() !== "") {
        // Stream ended mid-row (incomplete NDJSON line).
        throw new InvokeStreamAborted({
          packageName,
          functionName,
          rowIndex,
          message:
            "invoke stream ended mid-row for " +
            packageName +
            "." +
            functionName +
            " at row " +
            String(rowIndex),
        });
      }
    } finally {
      try {
        reader.releaseLock();
      } catch {
        // ignore release errors after cancel
      }
    }
  }
}

/** Instantiates a connect-only HTTP invoke client. Never spawns in production. */
export function createInvokeClient(config) {
  // resolveTransportMode runs in the constructor; spawn is never started here.
  return new HttpInvokeClient(config);
}

let defaultClient;
let defaultConfig = {};
let activeTestTransportResolver;

/**
 * Internal. Registered by dist/testing.js so withForstTestScope reaches flat exports
 * through getDefaultInvokeClient (options.transport seam).
 */
export function setActiveTestTransportResolver(resolve) {
  activeTestTransportResolver = resolve;
}

/**
 * Merge config into the default singleton used by flat package exports.
 * Resets the cached client so the next call picks up middleware and base URL.
 */
export function configureDefaultInvokeClient(config) {
  defaultConfig = { ...defaultConfig, ...(config ?? {}) };
  defaultClient = undefined;
}

/** Lazy process-wide default client for generated call sites. */
export function getDefaultInvokeClient() {
  if (typeof activeTestTransportResolver === "function") {
    const scoped = activeTestTransportResolver();
    if (scoped) {
      return scoped;
    }
  }
  if (!defaultClient) {
    defaultClient = createInvokeClient(defaultConfig);
  }
  return defaultClient;
}

/** Clears the default singleton so tests can swap transport config between cases. */
export function resetDefaultInvokeClientForTest() {
  defaultClient = undefined;
}
`
