package transformerts

import (
	"fmt"
	"sort"
	"strings"

	"forst/internal/invokeserver"
)

// DefaultInvokePort is the embedded invoke listen port used when EmitTransport*
// is called with an empty port. Matches ftconfig.DefaultEmbeddedInvokePort.
const DefaultInvokePort = "6321"

// TransportModuleSpecifier is the relative ESM import path for the private runtime module.
const TransportModuleSpecifier = TransportRuntimeModuleSpecifier

// EmitStreamingResultTypeDeclaration returns the StreamingResult interface copied into
// generated types.d.ts when any exported function uses streaming. Kept in sync with
// the interface inside EmitTransportDTS / EmitTransportTypeScript.
func EmitStreamingResultTypeDeclaration() string {
	return `/** One NDJSON line from a streaming POST /invoke response. */
export interface StreamingResult {
  data: any;
  status: string;
  error?: string;
}`
}

// functionsNeedStreamingResult reports whether types.d.ts must include StreamingResult.
func functionsNeedStreamingResult(functions []FunctionSignature) bool {
	for i := range functions {
		if functions[i].StreamingRowType != "" {
			return true
		}
	}
	return false
}

// transportInvokePortPlaceholder is substituted with the resolved invoke port.
const transportInvokePortPlaceholder = "{{INVOKE_PORT}}"

// transportContractVersionPlaceholder is substituted with invokeserver.HTTPContractVersion.
const transportContractVersionPlaceholder = "{{CONTRACT_VERSION}}"

func resolveTransportInvokePort(invokePort string) string {
	if invokePort == "" {
		return DefaultInvokePort
	}
	return invokePort
}

func substituteInvokePort(src, invokePort string) string {
	return strings.ReplaceAll(src, transportInvokePortPlaceholder, resolveTransportInvokePort(invokePort))
}

func substituteContractVersion(src string) string {
	return strings.ReplaceAll(src, transportContractVersionPlaceholder, invokeserver.HTTPContractVersion)
}

func substituteTransportPlaceholders(src, invokePort string) string {
	return substituteContractVersion(substituteInvokePort(src, invokePort))
}

func transportFileHeader(invokePort string, runtime ClientRuntime) string {
	header := substituteInvokePort(`// Auto-generated Forst invoke transport (connect-only).
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.
//
// Connect to embedded invoke: FORST_BASE_URL=http://127.0.0.1:{{INVOKE_PORT}}
// Env overrides (first wins): FORST_INVOKE_URL, FORST_BASE_URL, FORST_DEV_URL
// Production (NODE_ENV=production): FORST_BASE_URL (or config) is required; Never spawns.

`, invokePort)
	if runtime == RuntimeEffect {
		header = strings.Replace(header, "// Do not edit by hand.\n", "// Effect mode. Do not edit by hand.\n", 1)
	}
	return header
}

func transportErrorsImport(runtime ClientRuntime) string {
	pkg := errorsPackageImport(runtime)
	return "import {\n  " + strings.Join(ErrorClassNames(), ",\n  ") + ",\n} from \"" + pkg + "\";\n\n"
}

func transportDomainErrorDecodeBlock(domainPackages []PackageDomainErrorEmit, runtime ClientRuntime) string {
	pkg := errorsPackageImport(runtime)
	var b strings.Builder
	b.WriteString(`// Auto-generated domain error wire decode for transport.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

`)
	fmt.Fprintf(&b, "import { ForstUnknownFailure as %s } from %q;\n", unknownFailureDecodeImport, pkg)
	for _, emit := range domainPackages {
		if len(emit.Errors) == 0 {
			continue
		}
		fmt.Fprintf(&b, "import * as $%s from \"../pkg/%s.js\";\n", emit.ForstPackage, PackageDomainErrorsFileStem(emit.ForstPackage))
	}
	b.WriteString("\nconst packageDomainErrorRegistries = {\n")
	for _, emit := range domainPackages {
		if len(emit.Errors) == 0 {
			continue
		}
		fmt.Fprintf(&b, "  %q: {\n", emit.ForstPackage)
		sorted := append([]ErrorClass(nil), emit.Errors...)
		sort.Slice(sorted, func(i, j int) bool {
			return domainWireTag(sorted[i]) < domainWireTag(sorted[j])
		})
		for _, c := range sorted {
			fmt.Fprintf(&b, "    %q: $%s.%s,\n", domainWireTag(c), emit.ForstPackage, GeneratedTypeExport(c.Name))
		}
		b.WriteString("  },\n")
	}
	b.WriteString("};\n\n")
	b.WriteString(`export function decodeDomainError(errorValue, ctx = {}) {
  const registry = ctx?.packageName ? packageDomainErrorRegistries[ctx.packageName] : undefined;
  const tag = errorValue?.tag;
  const Ctor = registry && tag ? registry[tag] : undefined;
  const payload =
    errorValue?.payload && typeof errorValue.payload === "object"
      ? errorValue.payload
      : {};
  const base = {
    message: errorValue?.message ?? ctx.serverError ?? tag ?? "ForstUnknownFailure",
    serverError: ctx.serverError,
    packageName: ctx.packageName,
    functionName: ctx.functionName,
  };
  if (!Ctor) {
    return new ` + unknownFailureDecodeImport + `({ ...base, tag });
  }
  return new Ctor({ ...payload, ...base });
}

`)
	return b.String()
}

func transportNodeImports() string {
	return `import { createHmac } from "node:crypto";
import { createReadStream, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import * as http from "node:http";

`
}

// EmitTransportErrorsESM returns dist/transport/errors.js (domain wire decode only).
func EmitTransportErrorsESM(domainPackages []PackageDomainErrorEmit, runtime ClientRuntime) string {
	return transportDomainErrorDecodeBlock(domainPackages, runtime)
}

// EmitTransportRuntimeESM returns dist/transport/runtime.js (HTTP invoke client).
func EmitTransportRuntimeESM(invokePort string, runtime ClientRuntime) string {
	return substituteTransportPlaceholders(
		transportFileHeader(invokePort, runtime)+
			`import { decodeDomainError } from "./errors.js";
`+
			transportErrorsImport(runtime)+
			transportNodeImports()+
			transportRuntimeESM,
		invokePort,
	)
}

// EmitTransportRuntimeDTS returns dist/transport/runtime.d.ts (full runtime surface for generated modules).
func EmitTransportRuntimeDTS() string {
	return `// Auto-generated Forst invoke transport runtime (private).
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

` + transportTypeDeclarations()
}

// EmitTransportPublicESM returns dist/$transport.js (public facade).
func EmitTransportPublicESM(npmPackageName string, runtime ClientRuntime) string {
	var b strings.Builder
	b.WriteString(`// Auto-generated public Forst transport wiring.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

export {
  configureDefaultInvokeClient,
} from "./transport/runtime.js";
`)
	if runtime == RuntimeEffect {
		b.WriteString("\n")
		b.WriteString(EmitEffectSupportESM(npmPackageName))
	}
	return b.String()
}

// EmitTransportPublicDTS returns dist/$transport.d.ts (public facade).
func EmitTransportPublicDTS(npmPackageName string, runtime ClientRuntime) string {
	var b strings.Builder
	b.WriteString(`// Auto-generated public Forst transport wiring.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

export { configureDefaultInvokeClient } from "./transport/runtime.js";
export type {
  ForstInvokeClient,
  ForstInvokeClientConfig,
  ForstInvokeMiddleware,
  InvokeCallOptions,
  InvokeContext,
  InvokeSuccess,
  StreamingResult,
} from "./transport/runtime.js";
`)
	if runtime == RuntimeEffect {
		b.WriteString("\n")
		b.WriteString(EmitEffectSupportDTS(npmPackageName))
	}
	return b.String()
}

// EmitTransportESM returns dist/transport/runtime.js (connect-only HTTP invoke + NDJSON stream).
func EmitTransportESM(invokePort string, runtime ClientRuntime, _ []PackageDomainErrorEmit) string {
	return EmitTransportRuntimeESM(invokePort, runtime)
}

// EmitTransportDTS returns dist/transport/runtime.d.ts for the private runtime module.
func EmitTransportDTS() string {
	return EmitTransportRuntimeDTS()
}

// EmitTransportTypeScript returns the TypeScript source for the generated package's
// inlined connect-only HTTP invoke transport (src/transport.ts during development).
//
// Built from the same runtime body as EmitTransportESM plus the type surface so the
// checked-in .ts source and the generated .js/.d.ts pair cannot drift. The shared runtime is plain
// JS, so the file starts with @ts-nocheck.
//
// invokePort is the default listen port embedded in the fallback base URL
// (http://127.0.0.1:<port>). Pass cfg.Server.EffectiveInvokePort() from generate.
// An empty invokePort uses DefaultInvokePort.
func EmitTransportTypeScript(invokePort string, runtime ClientRuntime, domainPackages []PackageDomainErrorEmit) string {
	return "// @ts-nocheck\n" +
		substituteTransportPlaceholders(
			transportFileHeader(invokePort, runtime)+
				`import { decodeDomainError } from "./errors.js";
`+
				transportErrorsImport(runtime)+
				transportNodeImports()+
				transportTypeDeclarations()+"\n"+
				transportRuntimeESM,
			invokePort,
		)
}

// transportTypeDeclarations returns the shared transport type surface for .ts and .d.ts emit.
func transportTypeDeclarations() string {
	return jsdocStreamingResult + `
export interface StreamingResult {
  data: any;
  status: string;
  error?: string;
}

` + jsdocInvokeSuccess + `
export interface InvokeSuccess<T = unknown> {
  success: true;
  result: T;
  output?: string;
  error?: string;
}

` + jsdocInvokeCallOptions + `
export interface InvokeCallOptions {
  signal?: AbortSignal;
  timeoutMs?: number;
  retries?: number;
  /** Per-call HTTP headers merged over config.headers. */
  headers?: Record<string, string>;
  /** Internal. Used by Effect mode and {@link withForstTestScope} to inject a transport. */
  transport?: ForstInvokeClient;
}

` + jsdocInvokeContext + `
export interface InvokeContext {
  packageName: string;
  functionName: string;
  attempt: number;
  startedAt: number;
}

` + jsdocForstInvokeMiddleware + `
export interface ForstInvokeMiddleware {
  onStart?(ctx: InvokeContext): void | Promise<void>;
  onSuccess?(ctx: InvokeContext, result: unknown): void | Promise<void>;
  /** error is {@link InvokeFailure} from @forst/errors when thrown by the transport. */
  onFailure?(ctx: InvokeContext, error: unknown): void | Promise<void>;
}

` + jsdocForstInvokeClientConfig + `
export interface ForstInvokeClientConfig {
  baseUrl?: string;
  /** Alias accepted for parity with older clients. */
  devServerUrl?: string;
  /** Project root for .forst/invoke.ready and FORST_INVOKE_TOKEN discovery. */
  rootDir?: string;
  timeout?: number;
  retries?: number;
  /** Opt-in spawn of forst dev (ignored when NODE_ENV=production). Off by default. */
  allowSpawn?: boolean;
  /** "dev" opts into spawn path (same as allowSpawn). Off by default. */
  transport?: "http" | "dev";
  /** Injectable fetch for tests. */
  fetchFn?: typeof fetch;
  /** Default HTTP headers merged into every invoke (for example Authorization). */
  headers?: Record<string, string>;
  /** Observability middleware chain (request start / success / failure). */
  middleware?: ForstInvokeMiddleware[];
  /** Override auth discovery (for example spawn handoff from {@link startForstTestServer}). */
  resolveAuth?: () => { token: Uint8Array; generation: number } | undefined;
}

` + jsdocForstInvokeClient + `
export interface ForstInvokeClient {
  invokeFunction<T>(
    packageName: string,
    functionName: string,
    args?: unknown[],
    options?: InvokeCallOptions
  ): Promise<InvokeSuccess<T>>;
  invokeStream<T = unknown>(
    packageName: string,
    functionName: string,
    args?: unknown[],
    options?: InvokeCallOptions
  ): AsyncGenerator<StreamingResult & { data?: T }, void, undefined>;
}

` + jsdocCreateInvokeClient + `
export declare function createInvokeClient(
  config?: ForstInvokeClientConfig
): ForstInvokeClient;

` + jsdocGetDefaultInvokeClient + `
export declare function getDefaultInvokeClient(): ForstInvokeClient;

` + jsdocConfigureDefaultInvokeClient + `
export declare function configureDefaultInvokeClient(
  config: ForstInvokeClientConfig
): void;

` + jsdocResetDefaultInvokeClientForTest + `
export declare function resetDefaultInvokeClientForTest(): void;

/**
 * Internal. The testing subpath registers a resolver so flat exports honour
 * withForstTestScope without mutating module-level override maps.
 */
export declare function setActiveTestTransportResolver(
  resolve: (() => ForstInvokeClient | undefined) | undefined
): void;
`
}

// transportRuntimeESM is the shared connect-only HTTP + NDJSON implementation.
// Used by EmitTransportESM and EmitTransportTypeScript (valid as both .js and .ts).
// Placeholders: {{INVOKE_PORT}}
// Throws tagged failures from @forst/errors. Domain wire errors decode via decodeDomainError.
const transportRuntimeESM = `const defaultInvokeBaseUrl = "http://127.0.0.1:{{INVOKE_PORT}}";
const EXPECTED_CONTRACT_VERSION = "{{CONTRACT_VERSION}}";

const RESERVED_INVOKE_HEADERS = new Set([
  "x-forst-invoke-proof",
  "x-forst-invoke-generation",
  "x-forst-invoke-nonce",
  "x-forst-invoke-token",
]);
const INVOKE_PROOF_VERSION = "forst-invoke-v1";

function stripReservedHeaders(headers) {
  const out = {};
  for (const [key, value] of Object.entries(headers ?? {})) {
    if (!RESERVED_INVOKE_HEADERS.has(String(key).toLowerCase())) {
      out[key] = value;
    }
  }
  return out;
}

function mergeHeaders(config, options) {
  const out = { "Content-Type": "application/json" };
  const cfgHeaders = stripReservedHeaders(config?.headers);
  for (const [key, value] of Object.entries(cfgHeaders)) {
    if (value !== undefined && value !== null) {
      out[key] = String(value);
    }
  }
  const callHeaders = stripReservedHeaders(options?.headers);
  for (const [key, value] of Object.entries(callHeaders)) {
    if (value !== undefined && value !== null) {
      out[key] = String(value);
    }
  }
  return out;
}

function computeInvokeProof(token, generation, nonce) {
  return createHmac("sha256", token)
    .update(INVOKE_PROOF_VERSION + "|" + generation + "|" + nonce)
    .digest("base64url");
}

function readInvokeReadySocketPath(boundaryRoot) {
  const root = boundaryRoot || process.cwd();
  const readyPath = join(root, ".forst", "invoke.ready");
  if (!existsSync(readyPath)) {
    return undefined;
  }
  try {
    const ready = JSON.parse(readFileSync(readyPath, "utf8"));
    const socketPath =
      typeof ready.socketPath === "string" ? ready.socketPath.trim() : "";
    return socketPath || undefined;
  } catch {
    return undefined;
  }
}

function readInvokeTokenFromEnv() {
  const raw = String(process.env.FORST_INVOKE_TOKEN ?? "").trim();
  if (!raw) {
    return undefined;
  }
  try {
    const token = Buffer.from(raw, "base64url");
    if (!token.length) {
      return undefined;
    }
    return token;
  } catch {
    return undefined;
  }
}

function readInvokeReadyAuth(boundaryRoot) {
  const root = boundaryRoot || process.cwd();
  const readyPath = join(root, ".forst", "invoke.ready");
  if (!existsSync(readyPath)) {
    return undefined;
  }
  try {
    const ready = JSON.parse(readFileSync(readyPath, "utf8"));
    if (ready?.tokenDelivery === "handoff") {
      return undefined;
    }
    const generation = Number(ready.generation ?? 0);
    if (!Number.isFinite(generation) || generation <= 0) {
      return undefined;
    }
    let token = readInvokeTokenFromEnv();
    if (!token && ready?.tokenDelivery !== "env") {
      const tokenPath = join(root, ".forst", "invoke.token");
      if (existsSync(tokenPath)) {
        const tokenB64 = String(readFileSync(tokenPath, "utf8")).trim();
        token = Buffer.from(tokenB64, "base64url");
      }
    }
    if (!token || !token.length) {
      return undefined;
    }
    return {
      token,
      generation,
      url: typeof ready.url === "string" ? ready.url : undefined,
      socketPath:
        typeof ready.socketPath === "string" ? ready.socketPath : undefined,
    };
  } catch {
    return undefined;
  }
}

const envInvokeAuthRecvFd = "FORST_INVOKE_AUTH_RECV_FD";

/** @type {{ generation: number; token: Buffer } | undefined} */
let hostInvokeAuth;
let hostInvokeAuthListenerStarted = false;

function parseHostInvokeAuthHandoffLine(line) {
  let payload;
  try {
    payload = JSON.parse(line);
  } catch {
    return undefined;
  }
  if (
    payload === null ||
    typeof payload !== "object" ||
    Array.isArray(payload) ||
    payload.generation === undefined ||
    typeof payload.generation !== "number" ||
    !Number.isSafeInteger(payload.generation) ||
    payload.generation < 0 ||
    typeof payload.token !== "string" ||
    payload.token.trim() === ""
  ) {
    return undefined;
  }
  const token = Buffer.from(payload.token, "base64url");
  if (!token.length) {
    return undefined;
  }
  return { generation: payload.generation, token };
}

function storeHostInvokeAuthHandoff(handoff) {
  if (hostInvokeAuth?.token) {
    hostInvokeAuth.token.fill(0);
  }
  hostInvokeAuth = handoff;
}

async function consumeHostInvokeAuthStream(stream) {
  let buffer = "";
  for await (const chunk of stream) {
    buffer += chunk.toString();
    for (;;) {
      const newline = buffer.indexOf("\n");
      if (newline < 0) {
        break;
      }
      const line = buffer.slice(0, newline).trim();
      buffer = buffer.slice(newline + 1);
      if (line === "") {
        continue;
      }
      const handoff = parseHostInvokeAuthHandoffLine(line);
      if (handoff) {
        storeHostInvokeAuthHandoff(handoff);
      }
    }
  }
}

function startHostInvokeAuthRecvListener() {
  if (hostInvokeAuthListenerStarted) {
    return;
  }
  hostInvokeAuthListenerStarted = true;
  const raw = process.env[envInvokeAuthRecvFd]?.trim();
  if (!raw) {
    return;
  }
  const fd = Number(raw);
  if (!Number.isInteger(fd) || fd < 3) {
    return;
  }
  const stream = createReadStream(null, { fd, autoClose: false });
  stream.on("error", () => {
    // host relay closed or fd invalid
  });
  void consumeHostInvokeAuthStream(stream).catch(() => {
    // host relay closed
  });
}

function resolveHostInvokeAuthHandoff() {
  if (!hostInvokeAuth) {
    return undefined;
  }
  return {
    generation: hostInvokeAuth.generation,
    token: hostInvokeAuth.token,
  };
}

function isUnixSocketSupported() {
  return process.platform !== "win32";
}

function requestOverUnixSocket(socketPath, path, init = {}) {
  return new Promise((resolve, reject) => {
    const headers = { ...(init.headers ?? {}) };
    const req = http.request(
      {
        socketPath,
        path,
        method: init.method ?? "GET",
        headers,
      },
      (res) => {
        const chunks = [];
        res.on("data", (chunk) => {
          chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
        });
        res.on("end", () => {
          resolve(
            new Response(Buffer.concat(chunks), {
              status: res.statusCode ?? 500,
              headers: res.headers,
            })
          );
        });
      }
    );
    req.on("error", reject);
    if (typeof init.body === "string") {
      req.write(init.body);
    }
    req.end();
  });
}

function authDisabledByEnv() {
  const v = String(process.env.FORST_INVOKE_AUTH ?? "")
    .trim()
    .toLowerCase();
  return v === "off" || v === "0" || v === "false";
}

let invokeAuthDisabledWarningLogged = false;

function warnIfInvokeAuthDisabled() {
  if (invokeAuthDisabledWarningLogged || !authDisabledByEnv()) {
    return;
  }
  invokeAuthDisabledWarningLogged = true;
  console.warn(
    "forst invoke: authentication disabled via FORST_INVOKE_AUTH; invoke RPC accepts requests without HMAC proof (local debugging / tests only)"
  );
}

function checkContractVersion(response, packageName, functionName) {
  const got = response.headers.get("X-Forst-Contract-Version");
  if (got && got !== EXPECTED_CONTRACT_VERSION) {
    throw new ContractVersionMismatch({
      expectedContractVersion: EXPECTED_CONTRACT_VERSION,
      serverContractVersion: got,
      message:
        "invoke contract version mismatch for " +
        packageName +
        "." +
        functionName +
        ": expected " +
        EXPECTED_CONTRACT_VERSION +
        ", got " +
        got,
    });
  }
}

async function retryDelayMs(attempt) {
  const base = 100;
  const cap = 2000;
  const exp = Math.min(cap, base * Math.pow(2, attempt));
  const jitter = Math.floor(Math.random() * exp * 0.25);
  await new Promise((resolve) => setTimeout(resolve, exp + jitter));
}

function resolveEnvBaseUrl() {
  const proc = typeof process !== "undefined" ? process : undefined;
  const env = proc?.env;
  if (!env) {
    return undefined;
  }
  return env.FORST_INVOKE_URL ?? env.FORST_BASE_URL ?? env.FORST_DEV_URL;
}

function resolveConfiguredBaseUrl(config) {
  const raw = config?.baseUrl ?? config?.devServerUrl ?? resolveEnvBaseUrl();
  if (!raw) {
    return undefined;
  }
  return String(raw).replace(/\/$/, "");
}

function resolveBaseUrl(config) {
  return resolveConfiguredBaseUrl(config) ?? defaultInvokeBaseUrl.replace(/\/$/, "");
}

function nodeEnv() {
  const proc = typeof process !== "undefined" ? process : undefined;
  return proc?.env?.NODE_ENV;
}

/**
 * Resolve transport mode. Spawn is opt-in and forbidden in production (F-12).
 * Full forst dev spawn is deferred; "dev" still connects over HTTP for now.
 */
function resolveTransportMode(config) {
  const env = nodeEnv();
  const proc = typeof process !== "undefined" ? process : undefined;
  if (proc?.env?.FORST_SKIP_SPAWN === "1") {
    if (env === "production" && !resolveConfiguredBaseUrl(config)) {
      throw new InvokeBaseUrlMissing({
        envVar: "FORST_BASE_URL",
        nodeEnv: "production",
        message: "FORST_BASE_URL is required when NODE_ENV=production",
      });
    }
    return "http";
  }
  if (env === "production") {
    if (!resolveConfiguredBaseUrl(config)) {
      throw new InvokeBaseUrlMissing({
        envVar: "FORST_BASE_URL",
        nodeEnv: "production",
        message: "FORST_BASE_URL is required when NODE_ENV=production",
      });
    }
    // Never spawn in production, even if allowSpawn / transport: "dev" is set.
    return "http";
  }
  if (config?.transport === "dev" || config?.allowSpawn === true) {
    return "dev";
  }
  return "http";
}

function combineSignals(timeoutMs, signal) {
  if (timeoutMs !== undefined && timeoutMs > 0) {
    const timeoutSignal = AbortSignal.timeout(timeoutMs);
    if (!signal) {
      return timeoutSignal;
    }
    if (typeof AbortSignal.any === "function") {
      return AbortSignal.any([signal, timeoutSignal]);
    }
    return timeoutSignal;
  }
  return signal;
}

function isAbortError(err) {
  if (err === null || typeof err !== "object") {
    return false;
  }
  const name = err.name;
  return name === "AbortError" || name === "TimeoutError";
}

function shouldRetryInvokeFailure(err) {
  if (!err || typeof err !== "object") {
    return false;
  }
  const tag = err._tag;
  return tag === "InvokeUnreachable" || tag === "InvokeHttpFailure";
}

class HttpInvokeClient {
  constructor(config) {
    resolveTransportMode(config);
    if (authDisabledByEnv()) {
      warnIfInvokeAuthDisabled();
    }
    this.config = config ?? {};
    this.boundaryRoot = config?.rootDir ?? process.cwd();
    this.baseUrl = resolveBaseUrl(config);
    this.timeoutMs = config?.timeout ?? 30_000;
    this.retries = config?.retries ?? 0;
    this.fetchFn = config?.fetchFn ?? fetch.bind(globalThis);
    this.middleware = config?.middleware ?? [];
    this.headers = config?.headers ?? {};
  }

  resolveAuthState() {
    if (authDisabledByEnv()) {
      return undefined;
    }
    if (typeof this.config.resolveAuth === "function") {
      return this.config.resolveAuth();
    }
    const handoff = resolveHostInvokeAuthHandoff();
    if (handoff) {
      return handoff;
    }
    return readInvokeReadyAuth(this.boundaryRoot);
  }

  resolveSocketPath() {
    return readInvokeReadySocketPath(this.boundaryRoot);
  }

  async dial(path, init) {
    const socketPath = this.resolveSocketPath();
    if (socketPath && isUnixSocketSupported()) {
      return requestOverUnixSocket(socketPath, path, init);
    }
    return this.fetchFn(this.baseUrl + path, init);
  }

  async fetchWithAuth(path, init, options) {
    const headers = mergeHeaders({ headers: this.headers }, options);
    const auth = this.resolveAuthState();
    if (auth && path !== "/invoke/challenge" && path !== "/health") {
      const challengeRes = await this.dial("/invoke/challenge", {
        method: "GET",
        signal: init?.signal,
      });
      if (!challengeRes.ok) {
        const responseText = await challengeRes.text();
        throw new InvokeHttpFailure({
          packageName: "",
          functionName: "challenge",
          status: challengeRes.status,
          responseText,
          message:
            "invoke challenge failed: HTTP " + String(challengeRes.status),
        });
      }
      const payload = await challengeRes.json();
      const raw = payload?.result;
      const challenge =
        typeof raw === "string" ? JSON.parse(raw) : raw;
      if (!challenge?.nonce) {
        throw new InvokeRejected({
          packageName: "",
          functionName: "challenge",
          serverError: "invoke challenge missing nonce",
          message: "invoke challenge missing nonce",
        });
      }
      headers["X-Forst-Invoke-Nonce"] = challenge.nonce;
      headers["X-Forst-Invoke-Generation"] = String(auth.generation);
      headers["X-Forst-Invoke-Proof"] = computeInvokeProof(
        auth.token,
        auth.generation,
        challenge.nonce
      );
    }
    return this.dial(path, { ...init, headers });
  }

  async runMiddleware(hook, ctx, arg) {
    for (const mw of this.middleware) {
      const fn = mw?.[hook];
      if (typeof fn === "function") {
        await fn(ctx, arg);
      }
    }
  }

  async invokeFunction(packageName, functionName, args = [], options) {
    const retries = options?.retries ?? this.retries;
    let attempt = 0;
    const startedAt = Date.now();
    for (;;) {
      const ctx = {
        packageName,
        functionName,
        attempt: attempt + 1,
        startedAt,
      };
      await this.runMiddleware("onStart", ctx);
      try {
        const result = await this.invokeFunctionOnce(
          packageName,
          functionName,
          args,
          options
        );
        await this.runMiddleware("onSuccess", ctx, result);
        return result;
      } catch (err) {
        if (attempt >= retries || !shouldRetryInvokeFailure(err)) {
          await this.runMiddleware("onFailure", ctx, err);
          throw err;
        }
        attempt += 1;
        await retryDelayMs(attempt);
      }
    }
  }

  async invokeFunctionOnce(packageName, functionName, args = [], options) {
    const timeoutMs = options?.timeoutMs ?? this.timeoutMs;
    const signal = combineSignals(timeoutMs, options?.signal);
    const body = JSON.stringify({
      package: packageName,
      function: functionName,
      args,
    });
    let response;
    try {
      response = await this.fetchWithAuth(
        "/invoke",
        {
          method: "POST",
          body,
          signal,
        },
        options
      );
    } catch (err) {
      if (isAbortError(err)) {
        throw new InvokeTimedOut({
          packageName,
          functionName,
          timeoutMs,
          message:
            "invoke timed out for " +
            packageName +
            "." +
            functionName,
        });
      }
      throw new InvokeUnreachable({
        packageName,
        functionName,
        baseUrl: this.baseUrl,
        message:
          "invoke unreachable " +
          packageName +
          "." +
          functionName +
          " at " +
          this.baseUrl +
          ": " +
          String(err),
      });
    }
    const responseText = await response.text();
    checkContractVersion(response, packageName, functionName);
    if (!response.ok) {
      throw new InvokeHttpFailure({
        packageName,
        functionName,
        status: response.status,
        responseText,
        message:
          "invoke HTTP " +
          String(response.status) +
          " for " +
          packageName +
          "." +
          functionName +
          ": " +
          responseText,
      });
    }
    let envelope;
    try {
      envelope = JSON.parse(responseText);
    } catch {
      throw new InvokeRejected({
        packageName,
        functionName,
        serverError: "invoke response is not JSON: " + responseText,
        message:
          "invoke response is not JSON for " +
          packageName +
          "." +
          functionName,
      });
    }
    if (!envelope.success) {
      if (envelope.errorValue) {
        throw decodeDomainError(envelope.errorValue, {
          packageName,
          functionName,
          serverError: envelope.error,
        });
      }
      throw new InvokeRejected({
        packageName,
        functionName,
        serverError: envelope.error,
        message:
          envelope.error ??
          "invoke rejected for " + packageName + "." + functionName,
      });
    }
    if (envelope.result === undefined) {
      throw new InvokeRejected({
        packageName,
        functionName,
        serverError: envelope.error,
        message:
          envelope.error ??
          "invoke response missing result for " +
            packageName +
            "." +
            functionName,
      });
    }
    return {
      success: true,
      result: envelope.result,
      output: envelope.output,
      error: envelope.error,
    };
  }

  async *invokeStream(packageName, functionName, args = [], options) {
    const ctx = {
      packageName,
      functionName,
      attempt: 1,
      startedAt: Date.now(),
    };
    await this.runMiddleware("onStart", ctx);
    try {
      yield* this.invokeStreamBody(packageName, functionName, args, options);
      await this.runMiddleware("onSuccess", ctx, undefined);
    } catch (err) {
      await this.runMiddleware("onFailure", ctx, err);
      throw err;
    }
  }

  async *invokeStreamBody(packageName, functionName, args = [], options) {
    const timeoutMs = options?.timeoutMs ?? this.timeoutMs;
    const signal = combineSignals(timeoutMs, options?.signal);
    const body = JSON.stringify({
      package: packageName,
      function: functionName,
      args,
      streaming: true,
    });
    let response;
    try {
      response = await this.fetchWithAuth(
        "/invoke",
        {
          method: "POST",
          body,
          signal,
        },
        options
      );
    } catch (err) {
      if (isAbortError(err)) {
        return;
      }
      throw new InvokeUnreachable({
        packageName,
        functionName,
        baseUrl: this.baseUrl,
        message:
          "invoke stream unreachable " +
          packageName +
          "." +
          functionName +
          " at " +
          this.baseUrl +
          ": " +
          String(err),
      });
    }
    if (!response.ok) {
      const responseText = await response.text();
      throw new InvokeHttpFailure({
        packageName,
        functionName,
        status: response.status,
        responseText,
        message:
          "invoke stream HTTP " +
          String(response.status) +
          " for " +
          packageName +
          "." +
          functionName +
          ": " +
          responseText,
      });
    }
    checkContractVersion(response, packageName, functionName);
    if (!response.body) {
      throw new InvokeStreamAborted({
        packageName,
        functionName,
        rowIndex: 0,
        message:
          "invoke stream response missing body for " +
          packageName +
          "." +
          functionName,
      });
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    let rowIndex = 0;

    const abortAndEnd = () => {
      if (signal?.aborted) {
        try {
          void reader.cancel();
        } catch {
          // ignore cancel errors
        }
        return true;
      }
      return false;
    };

    try {
      while (true) {
        if (abortAndEnd()) {
          return;
        }
        let done = false;
        let value;
        try {
          const chunk = await reader.read();
          done = chunk.done;
          value = chunk.value;
        } catch (err) {
          if (isAbortError(err) || signal?.aborted) {
            return;
          }
          throw err;
        }
        if (done) {
          break;
        }
        buffer += decoder.decode(value, { stream: true });
        let newline = buffer.indexOf("\n");
        while (newline >= 0) {
          const line = buffer.slice(0, newline).replace(/\r$/, "");
          buffer = buffer.slice(newline + 1);
          newline = buffer.indexOf("\n");
          if (line.trim() === "") {
            continue;
          }
          let parsed;
          try {
            parsed = JSON.parse(line);
          } catch {
            throw new InvokeStreamAborted({
              packageName,
              functionName,
              rowIndex,
              message:
                "invoke stream row failed to parse for " +
                packageName +
                "." +
                functionName +
                " at row " +
                String(rowIndex),
            });
          }
          rowIndex += 1;
          yield parsed;
          if (abortAndEnd()) {
            return;
          }
        }
      }
      buffer += decoder.decode();
      const trailing = buffer.replace(/\r$/, "");
      if (trailing.trim() !== "") {
        // Stream ended mid-row (incomplete NDJSON line).
        throw new InvokeStreamAborted({
          packageName,
          functionName,
          rowIndex,
          message:
            "invoke stream ended mid-row for " +
            packageName +
            "." +
            functionName +
            " at row " +
            String(rowIndex),
        });
      }
    } finally {
      try {
        reader.releaseLock();
      } catch {
        // ignore release errors after cancel
      }
    }
  }
}
` + jsdocCreateInvokeClient + `
export function createInvokeClient(config) {
  // resolveTransportMode runs in the constructor; spawn is never started here.
  return new HttpInvokeClient(config);
}

let defaultClient;
let defaultConfig = {};
let activeTestTransportResolver;

/**
 * Internal. Registered by dist/testing.js so withForstTestScope reaches flat exports
 * through getDefaultInvokeClient (options.transport seam).
 */
export function setActiveTestTransportResolver(resolve) {
  activeTestTransportResolver = resolve;
}

` + jsdocConfigureDefaultInvokeClient + `
export function configureDefaultInvokeClient(config) {
  startHostInvokeAuthRecvListener();
  defaultConfig = { ...defaultConfig, ...(config ?? {}) };
  defaultClient = undefined;
}

` + jsdocGetDefaultInvokeClient + `
export function getDefaultInvokeClient() {
  if (typeof activeTestTransportResolver === "function") {
    const scoped = activeTestTransportResolver();
    if (scoped) {
      return scoped;
    }
  }
  if (!defaultClient) {
    defaultClient = createInvokeClient(defaultConfig);
  }
  return defaultClient;
}

` + jsdocResetDefaultInvokeClientForTest + `
export function resetDefaultInvokeClientForTest() {
  defaultClient = undefined;
}

startHostInvokeAuthRecvListener();
`
