// Auto-generated domain error namespaces for this project.
// Generated by Forst TypeScript Transformer.
// Invoke/harness failures: import from "@forst/errors/effect".
// Do not edit by hand.

export {};
