// Auto-generated domain error namespaces for this project.
// Generated by Forst TypeScript Transformer.
// Invoke/harness failures: use @forst/errors/effect directly (not re-exported here).
// Do not edit by hand.

export {};
