// Auto-generated Forst domain errors.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

import { Data } from "effect";

export declare class ForstUnknownFailure extends Data.TaggedError("@forst/gen/ForstUnknownFailure")<{
  readonly serverError?: string;
  readonly tag?: string;
  readonly packageName?: string;
  readonly functionName?: string;
  readonly message?: string;
}> {}

export type ForstError = ForstUnknownFailure;

export declare const DOMAIN_ERROR_REGISTRY: Record<string, new (props: Record<string, unknown>) => Error>;

export declare function decodeDomainError(
  errorValue: { tag?: string; payload?: Record<string, unknown>; message?: string } | undefined,
  ctx?: { packageName?: string; functionName?: string; serverError?: string }
): ForstError;
