// Auto-generated Forst domain errors.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

import { Data } from "effect";

export class ForstUnknownFailure extends Data.TaggedError("@forst/gen/ForstUnknownFailure") {}


export const DOMAIN_ERROR_REGISTRY = {
};

export const decodeDomainError = (errorValue, ctx = {}) => {
  const tag = errorValue?.tag;
  const Ctor = tag ? DOMAIN_ERROR_REGISTRY[tag] : undefined;
  const payload =
    errorValue?.payload && typeof errorValue.payload === "object"
      ? errorValue.payload
      : {};
  const base = {
    message: errorValue?.message ?? ctx.serverError ?? tag ?? "ForstUnknownFailure",
    serverError: ctx.serverError,
    packageName: ctx.packageName,
    functionName: ctx.functionName,
  };
  if (!Ctor) {
    return new ForstUnknownFailure({ ...base, tag });
  }
  return new Ctor({ ...payload, ...base });
};
