// Auto-generated Forst client errors (domain + shared re-exports).
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

import type { ForstUnknownFailure } from "@forst/errors/effect";
export type ForstError = ForstUnknownFailure;

export declare const DOMAIN_ERROR_REGISTRY: Record<string, new (props: Record<string, unknown>) => Error>;

export declare function decodeDomainError(
  errorValue: { tag?: string; payload?: Record<string, unknown>; message?: string } | undefined,
  ctx?: { packageName?: string; functionName?: string; serverError?: string }
): ForstError;

export {
  InvokeRejected,
  InvokeHttpFailure,
  InvokeTimedOut,
  InvokeUnreachable,
  InvokeBaseUrlMissing,
  InvokeStreamAborted,
  ContractVersionMismatch,
  isInvokeFailure,
  ForstUnknownFailure,
  ForstTestServerFailed,
} from "@forst/errors/effect";

export type { InvokeFailure } from "@forst/errors/effect";
