// Auto-generated Forst invoke transport errors.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

import { Data } from "effect";

export class InvokeRejected extends Data.TaggedError("@forst/InvokeRejected") {}

export class InvokeHttpFailure extends Data.TaggedError("@forst/InvokeHttpFailure") {}

export class InvokeTimedOut extends Data.TaggedError("@forst/InvokeTimedOut") {}

export class InvokeUnreachable extends Data.TaggedError("@forst/InvokeUnreachable") {}

export class InvokeBaseUrlMissing extends Data.TaggedError("@forst/InvokeBaseUrlMissing") {}

export class InvokeStreamAborted extends Data.TaggedError("@forst/InvokeStreamAborted") {}

export class ContractVersionMismatch extends Data.TaggedError("@forst/ContractVersionMismatch") {}


const INVOKE_FAILURE_TAGS = new Set([
  "@forst/InvokeRejected",
  "@forst/InvokeHttpFailure",
  "@forst/InvokeTimedOut",
  "@forst/InvokeUnreachable",
  "@forst/InvokeBaseUrlMissing",
  "@forst/InvokeStreamAborted",
  "@forst/ContractVersionMismatch",
]);

export const isInvokeFailure = (u) =>
  u instanceof Error && INVOKE_FAILURE_TAGS.has(u._tag);
