// Auto-generated Forst invoke transport errors.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

import { Data } from "effect";

export class InvokeRejected extends Data.TaggedError("@forst/gen/InvokeRejected") {}

export class InvokeHttpFailure extends Data.TaggedError("@forst/gen/InvokeHttpFailure") {}

export class InvokeTimedOut extends Data.TaggedError("@forst/gen/InvokeTimedOut") {}

export class InvokeUnreachable extends Data.TaggedError("@forst/gen/InvokeUnreachable") {}

export class InvokeBaseUrlMissing extends Data.TaggedError("@forst/gen/InvokeBaseUrlMissing") {}

export class InvokeStreamAborted extends Data.TaggedError("@forst/gen/InvokeStreamAborted") {}

export class ContractVersionMismatch extends Data.TaggedError("@forst/gen/ContractVersionMismatch") {}


const INVOKE_FAILURE_TAGS = new Set([
  "@forst/gen/InvokeRejected",
  "@forst/gen/InvokeHttpFailure",
  "@forst/gen/InvokeTimedOut",
  "@forst/gen/InvokeUnreachable",
  "@forst/gen/InvokeBaseUrlMissing",
  "@forst/gen/InvokeStreamAborted",
  "@forst/gen/ContractVersionMismatch",
]);

export const isInvokeFailure = (u) =>
  u instanceof Error && INVOKE_FAILURE_TAGS.has(u._tag);
