// Auto-generated Forst invoke transport errors.
// Generated by Forst TypeScript Transformer.
// Do not edit by hand.

import { Data } from "effect";

export declare class InvokeRejected extends Data.TaggedError("@forst/gen/InvokeRejected")<{
  readonly packageName: string;
  readonly functionName: string;
  readonly serverError?: string;
  readonly message?: string;
}> {}

export declare class InvokeHttpFailure extends Data.TaggedError("@forst/gen/InvokeHttpFailure")<{
  readonly packageName: string;
  readonly functionName: string;
  readonly status: number;
  readonly responseText: string;
  readonly message?: string;
}> {}

export declare class InvokeTimedOut extends Data.TaggedError("@forst/gen/InvokeTimedOut")<{
  readonly packageName: string;
  readonly functionName: string;
  readonly timeoutMs?: number;
  readonly message?: string;
}> {}

export declare class InvokeUnreachable extends Data.TaggedError("@forst/gen/InvokeUnreachable")<{
  readonly packageName: string;
  readonly functionName: string;
  readonly baseUrl: string;
  readonly message?: string;
}> {}

export declare class InvokeBaseUrlMissing extends Data.TaggedError("@forst/gen/InvokeBaseUrlMissing")<{
  readonly envVar: string;
  readonly nodeEnv: string;
  readonly message?: string;
}> {}

export declare class InvokeStreamAborted extends Data.TaggedError("@forst/gen/InvokeStreamAborted")<{
  readonly packageName: string;
  readonly functionName: string;
  readonly rowIndex: number;
  readonly message?: string;
}> {}

export declare class ContractVersionMismatch extends Data.TaggedError("@forst/gen/ContractVersionMismatch")<{
  readonly expectedContractVersion: string;
  readonly serverContractVersion: string;
  readonly message?: string;
}> {}

export type InvokeFailure =
  | InvokeRejected
  | InvokeHttpFailure
  | InvokeTimedOut
  | InvokeUnreachable
  | InvokeBaseUrlMissing
  | InvokeStreamAborted
  | ContractVersionMismatch
;

export declare function isInvokeFailure(u: unknown): u is InvokeFailure;
