// Auto-generated Forst Client
// Generated by Forst TypeScript Transformer

import { ForstSidecarClient as SidecarClient } from '@forst/sidecar';
import { echo } from '../generated/echo.client';
import { typesafety } from '../generated/typesafety.client';
import { user } from '../generated/user.client';

export interface ForstClientConfig {
  baseUrl?: string;
  timeout?: number;
  retries?: number;
}

export class ForstClient {
  private client: SidecarClient;
  public echo: ReturnType<typeof echo>;
  public typesafety: ReturnType<typeof typesafety>;
  public user: ReturnType<typeof user>;

  constructor(config?: ForstClientConfig) {
    const defaultConfig = {
      baseUrl: process.env.FORST_BASE_URL || 'http://localhost:8080',
      timeout: 30000,
      retries: 3,
      ...config,
    };

    this.client = new SidecarClient(defaultConfig);
    this.echo = echo(this.client);
    this.typesafety = typesafety(this.client);
    this.user = user(this.client);
  }
}

