// Auto-generated types for Forst client
// Generated by Forst TypeScript Transformer

// Type definitions
export interface User {
  email: string;
  id: string;
  name: string;
  age: number;
}

export interface CreateUserRequest {
  age: number;
  email: string;
  name: string;
}

export interface T_NGUd7jXQkPf {
  created_at: number;
  user: User;
}

// Function signatures
export function CreateUser(input: CreateUserRequest): Promise<T_NGUd7jXQkPf>;

export function GetUserById(id: string): Promise<User>;

export function UpdateUserAge(id: string, newAge: number): Promise<User>;
