version: "3"

vars:
  BINARY_NAME: forst
  BUILD_DIR: cmd/forst
  EXAMPLES_DIR: ../examples/in
  OUTPUT_DIR: ../examples/out

tasks:
  # Build tasks
  build:
    desc: Build the Forst compiler
    dir: forst
    cmds:
      - go build -o ../bin/{{.BINARY_NAME}} ./{{.BUILD_DIR}}
    sources:
      - ./**/*.go
    generates:
      - ../bin/{{.BINARY_NAME}}

  install:
    desc: Install the Forst compiler
    dir: forst
    cmds:
      - go install ./{{.BUILD_DIR}}

  clean:
    desc: Clean build artifacts
    dir: forst
    cmds:
      - rm -rf ../bin/
      - go clean -cache

  # Test tasks
  test:
    desc: Run all tests
    dir: forst
    cmds:
      - go test -v ./internal/...
      - go test -v ./cmd/forst/...

  test:unit:
    desc: Run unit tests only
    dir: forst
    cmds:
      - go test -v ./internal/...

  test:unit:parser:
    desc: Run unit tests for parser
    dir: forst
    cmds:
      - go test -v ./internal/parser/...

  test:unit:typechecker:
    desc: Run unit tests for typechecker
    dir: forst
    cmds:
      - go test -v ./internal/typechecker/...

  test:unit:transformer:
    desc: Run unit tests for transformer
    dir: forst
    cmds:
      - go test -v ./internal/transformer/...

  test:unit:lexer:
    desc: Run unit tests for lexer
    dir: forst
    cmds:
      - go test -v ./internal/lexer/...

  test:unit:ast:
    desc: Run unit tests for AST
    dir: forst
    cmds:
      - go test -v ./internal/ast/...

  test:integration:
    desc: Run integration tests (examples)
    dir: forst
    cmds:
      - go test -v ./cmd/forst/...

  test:coverage:
    desc: Run tests with coverage
    dir: forst
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
    generates:
      - coverage.out
      - coverage.html

  # Example compilation tasks
  example:
    desc: Compile a specific example file
    dir: forst
    cmds:
      - go run ./{{.BUILD_DIR}} run -trace -report-phases -- {{.CLI_ARGS}}
    vars:
      CLI_ARGS: '{{.CLI_ARGS | default "../examples/in/basic.ft"}}'

  example:basic:
    desc: Compile basic example
    dir: forst
    cmds:
      - go run ./{{.BUILD_DIR}} run -trace -report-phases -- {{.EXAMPLES_DIR}}/basic.ft

  example:function:
    desc: Compile function example
    dir: forst
    cmds:
      - go run ./{{.BUILD_DIR}} run -trace -report-phases -- {{.EXAMPLES_DIR}}/basic_function.ft

  example:ensure:
    desc: Compile ensure example
    dir: forst
    cmds:
      - go run ./{{.BUILD_DIR}} run -trace -report-phases -- {{.EXAMPLES_DIR}}/ensure.ft

  example:pointers:
    desc: Compile pointers example
    dir: forst
    cmds:
      - go run ./{{.BUILD_DIR}} run -trace -report-phases -- {{.EXAMPLES_DIR}}/pointers.ft

  example:guard:
    desc: Compile shape guard example
    dir: forst
    cmds:
      - go run ./{{.BUILD_DIR}} run -trace -report-phases -- {{.EXAMPLES_DIR}}/rfc/guard/shape_guard.ft

  example:basic-guard:
    desc: Compile basic guard example
    dir: forst
    cmds:
      - go run ./{{.BUILD_DIR}} run -trace -report-phases -- {{.EXAMPLES_DIR}}/rfc/guard/basic_guard.ft

  # Development tasks
  dev:watch:
    desc: Watch for changes and run tests
    cmds:
      - watchexec -r "task test"

  dev:lint:
    desc: Run linters
    dir: forst
    cmds:
      - golangci-lint run ./...

  dev:format:
    desc: Format code
    dir: forst
    cmds:
      - go fmt ./...

  dev:vet:
    desc: Run go vet
    dir: forst
    cmds:
      - go vet ./...

  # Documentation tasks
  docs:generate:
    desc: Generate documentation
    dir: forst
    cmds:
      - godoc -http=:6060

  # CI/CD tasks
  ci:test:
    desc: Run CI lint suite
    dir: forst
    cmds:
      - go test -race -covermode atomic -coverprofile=profile.cov ./cmd/forst/... ./internal/...
