// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: forst/node/v1/wire.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame is the length-prefixed v2 wire envelope.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Frame_Request
	//	*Frame_Response
	Body          isFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_forst_node_v1_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_forst_node_v1_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_forst_node_v1_wire_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Frame) GetBody() isFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Frame) GetRequest() *WireRequest {
	if x != nil {
		if x, ok := x.Body.(*Frame_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Frame) GetResponse() *WireResponse {
	if x != nil {
		if x, ok := x.Body.(*Frame_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isFrame_Body interface {
	isFrame_Body()
}

type Frame_Request struct {
	Request *WireRequest `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type Frame_Response struct {
	Response *WireResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*Frame_Request) isFrame_Body() {}

func (*Frame_Response) isFrame_Body() {}

type WireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireRequest) Reset() {
	*x = WireRequest{}
	mi := &file_forst_node_v1_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireRequest) ProtoMessage() {}

func (x *WireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forst_node_v1_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireRequest.ProtoReflect.Descriptor instead.
func (*WireRequest) Descriptor() ([]byte, []int) {
	return file_forst_node_v1_wire_proto_rawDescGZIP(), []int{1}
}

func (x *WireRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *WireRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type WireResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*WireResponse_OkJson
	//	*WireResponse_Err
	Result        isWireResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireResponse) Reset() {
	*x = WireResponse{}
	mi := &file_forst_node_v1_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireResponse) ProtoMessage() {}

func (x *WireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forst_node_v1_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireResponse.ProtoReflect.Descriptor instead.
func (*WireResponse) Descriptor() ([]byte, []int) {
	return file_forst_node_v1_wire_proto_rawDescGZIP(), []int{2}
}

func (x *WireResponse) GetResult() isWireResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WireResponse) GetOkJson() []byte {
	if x != nil {
		if x, ok := x.Result.(*WireResponse_OkJson); ok {
			return x.OkJson
		}
	}
	return nil
}

func (x *WireResponse) GetErr() *ErrorDetail {
	if x != nil {
		if x, ok := x.Result.(*WireResponse_Err); ok {
			return x.Err
		}
	}
	return nil
}

type isWireResponse_Result interface {
	isWireResponse_Result()
}

type WireResponse_OkJson struct {
	OkJson []byte `protobuf:"bytes,1,opt,name=ok_json,json=okJson,proto3,oneof"`
}

type WireResponse_Err struct {
	Err *ErrorDetail `protobuf:"bytes,2,opt,name=err,proto3,oneof"`
}

func (*WireResponse_OkJson) isWireResponse_Result() {}

func (*WireResponse_Err) isWireResponse_Result() {}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_forst_node_v1_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_forst_node_v1_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_forst_node_v1_wire_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorDetail) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type InitializeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResult) Reset() {
	*x = InitializeResult{}
	mi := &file_forst_node_v1_wire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResult) ProtoMessage() {}

func (x *InitializeResult) ProtoReflect() protoreflect.Message {
	mi := &file_forst_node_v1_wire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResult.ProtoReflect.Descriptor instead.
func (*InitializeResult) Descriptor() ([]byte, []int) {
	return file_forst_node_v1_wire_proto_rawDescGZIP(), []int{4}
}

func (x *InitializeResult) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type GenNextBatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*GenStepWire         `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenNextBatchResult) Reset() {
	*x = GenNextBatchResult{}
	mi := &file_forst_node_v1_wire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenNextBatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenNextBatchResult) ProtoMessage() {}

func (x *GenNextBatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_forst_node_v1_wire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenNextBatchResult.ProtoReflect.Descriptor instead.
func (*GenNextBatchResult) Descriptor() ([]byte, []int) {
	return file_forst_node_v1_wire_proto_rawDescGZIP(), []int{5}
}

func (x *GenNextBatchResult) GetSteps() []*GenStepWire {
	if x != nil {
		return x.Steps
	}
	return nil
}

type GenStepWire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ValueJson     []byte                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenStepWire) Reset() {
	*x = GenStepWire{}
	mi := &file_forst_node_v1_wire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenStepWire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenStepWire) ProtoMessage() {}

func (x *GenStepWire) ProtoReflect() protoreflect.Message {
	mi := &file_forst_node_v1_wire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenStepWire.ProtoReflect.Descriptor instead.
func (*GenStepWire) Descriptor() ([]byte, []int) {
	return file_forst_node_v1_wire_proto_rawDescGZIP(), []int{6}
}

func (x *GenStepWire) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GenStepWire) GetValueJson() []byte {
	if x != nil {
		return x.ValueJson
	}
	return nil
}

func (x *GenStepWire) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenStepWire) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

var File_forst_node_v1_wire_proto protoreflect.FileDescriptor

const file_forst_node_v1_wire_proto_rawDesc = "" +
	"\n" +
	"\x18forst/node/v1/wire.proto\x12\rforst.node.v1\"\x92\x01\n" +
	"\x05Frame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x126\n" +
	"\arequest\x18\x02 \x01(\v2\x1a.forst.node.v1.WireRequestH\x00R\arequest\x129\n" +
	"\bresponse\x18\x03 \x01(\v2\x1b.forst.node.v1.WireResponseH\x00R\bresponseB\x06\n" +
	"\x04body\"H\n" +
	"\vWireRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\"c\n" +
	"\fWireResponse\x12\x19\n" +
	"\aok_json\x18\x01 \x01(\fH\x00R\x06okJson\x12.\n" +
	"\x03err\x18\x02 \x01(\v2\x1a.forst.node.v1.ErrorDetailH\x00R\x03errB\b\n" +
	"\x06result\"X\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\fR\bdataJson\".\n" +
	"\x10InitializeResult\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\"F\n" +
	"\x12GenNextBatchResult\x120\n" +
	"\x05steps\x18\x01 \x03(\v2\x1a.forst.node.v1.GenStepWireR\x05steps\"w\n" +
	"\vGenStepWire\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\fR\tvalueJson\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\fR\bdataJsonB\x1dZ\x1bforst/internal/nodert/pb;pbb\x06proto3"

var (
	file_forst_node_v1_wire_proto_rawDescOnce sync.Once
	file_forst_node_v1_wire_proto_rawDescData []byte
)

func file_forst_node_v1_wire_proto_rawDescGZIP() []byte {
	file_forst_node_v1_wire_proto_rawDescOnce.Do(func() {
		file_forst_node_v1_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forst_node_v1_wire_proto_rawDesc), len(file_forst_node_v1_wire_proto_rawDesc)))
	})
	return file_forst_node_v1_wire_proto_rawDescData
}

var file_forst_node_v1_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_forst_node_v1_wire_proto_goTypes = []any{
	(*Frame)(nil),              // 0: forst.node.v1.Frame
	(*WireRequest)(nil),        // 1: forst.node.v1.WireRequest
	(*WireResponse)(nil),       // 2: forst.node.v1.WireResponse
	(*ErrorDetail)(nil),        // 3: forst.node.v1.ErrorDetail
	(*InitializeResult)(nil),   // 4: forst.node.v1.InitializeResult
	(*GenNextBatchResult)(nil), // 5: forst.node.v1.GenNextBatchResult
	(*GenStepWire)(nil),        // 6: forst.node.v1.GenStepWire
}
var file_forst_node_v1_wire_proto_depIdxs = []int32{
	1, // 0: forst.node.v1.Frame.request:type_name -> forst.node.v1.WireRequest
	2, // 1: forst.node.v1.Frame.response:type_name -> forst.node.v1.WireResponse
	3, // 2: forst.node.v1.WireResponse.err:type_name -> forst.node.v1.ErrorDetail
	6, // 3: forst.node.v1.GenNextBatchResult.steps:type_name -> forst.node.v1.GenStepWire
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_forst_node_v1_wire_proto_init() }
func file_forst_node_v1_wire_proto_init() {
	if File_forst_node_v1_wire_proto != nil {
		return
	}
	file_forst_node_v1_wire_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Request)(nil),
		(*Frame_Response)(nil),
	}
	file_forst_node_v1_wire_proto_msgTypes[2].OneofWrappers = []any{
		(*WireResponse_OkJson)(nil),
		(*WireResponse_Err)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forst_node_v1_wire_proto_rawDesc), len(file_forst_node_v1_wire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_forst_node_v1_wire_proto_goTypes,
		DependencyIndexes: file_forst_node_v1_wire_proto_depIdxs,
		MessageInfos:      file_forst_node_v1_wire_proto_msgTypes,
	}.Build()
	File_forst_node_v1_wire_proto = out.File
	file_forst_node_v1_wire_proto_goTypes = nil
	file_forst_node_v1_wire_proto_depIdxs = nil
}
