package main

import (
	"encoding/json"
	"fmt"
	"sort"

	"forst/internal/genplugin"
	"forst/internal/semantic"
)

type pluginOpt struct {
	Draft   string   `json:"draft"`
	Markers []string `json:"markers"`
}

type jsonSchemaDoc struct {
	Schema string         `json:"$schema"`
	Ref    string         `json:"$ref,omitempty"`
	Defs   map[string]any `json:"$defs"`
}

type schemaEnc struct {
	types    map[string]semantic.Type
	defIDs   map[string]string // type id → $defs key
	emitting map[string]bool
	warnings []string
}

func emitJSONSchema(req *semantic.GenerateRequest) (semantic.GenerateResponse, error) {
	opt := pluginOpt{Draft: "2020-12"}
	if req.Plugin != nil && len(req.Plugin.Opt) > 0 {
		_ = json.Unmarshal(req.Plugin.Opt, &opt)
	}
	if opt.Draft == "" {
		opt.Draft = "2020-12"
	}

	typeIDs := genplugin.ExportedPackageTypeIDs(req)
	if len(opt.Markers) > 0 {
		filtered := typeIDs[:0]
		for _, id := range typeIDs {
			if genplugin.HasMarker(req.Types[id], opt.Markers) {
				filtered = append(filtered, id)
			}
		}
		typeIDs = filtered
	}

	enc := &schemaEnc{
		types:    req.Types,
		defIDs:   map[string]string{},
		emitting: map[string]bool{},
	}
	used := map[string]int{}
	var emitIDs []string
	for _, id := range typeIDs {
		t := req.Types[id]
		if genplugin.IsRouterOnlyShape(t) || t.Kind == "func" {
			continue
		}
		name := uniqueDefName(id, used)
		enc.defIDs[id] = name
		emitIDs = append(emitIDs, id)
	}

	defs := make(map[string]any, len(emitIDs))
	var diags []semantic.Diagnostic
	for _, id := range emitIDs {
		t := req.Types[id]
		enc.warnings = nil
		enc.emitting[id] = true
		schema := enc.schemaOf(t, true)
		enc.emitting[id] = false
		defs[enc.defIDs[id]] = schema
		for _, w := range enc.warnings {
			diags = append(diags, semantic.Diagnostic{
				Severity: "warning",
				Message:  w,
				TypeID:   id,
				Span:     t.Span,
			})
		}
	}

	doc := jsonSchemaDoc{
		Schema: schemaDraftURL(opt.Draft),
		Defs:   defs,
	}
	if len(emitIDs) == 1 {
		doc.Ref = "#/$defs/" + enc.defIDs[emitIDs[0]]
	}

	raw, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return semantic.GenerateResponse{}, err
	}

	return semantic.GenerateResponse{
		ProtocolVersion: semantic.ProtocolVersion,
		Files: []semantic.OutputFile{
			{Path: "schema.json", Content: string(raw) + "\n"},
			{Path: "meta.json", Content: genplugin.MustJSON(map[string]any{
				"generator": "forst-gen-jsonschema",
				"version":   version,
				"draft":     opt.Draft,
				"typeCount": len(emitIDs),
			})},
			{Path: "README.txt", Content: fmt.Sprintf(
				"Generated by forst-gen-jsonschema %s. DO NOT EDIT.\nImport schema.json from your validation layer.\n",
				version,
			)},
		},
		Diagnostics: diags,
	}, nil
}

func uniqueDefName(id string, used map[string]int) string {
	base := genplugin.TypeShortName(id)
	if base == "" {
		base = "Type"
	}
	n := used[base]
	used[base] = n + 1
	if n == 0 {
		return base
	}
	return fmt.Sprintf("%s_%s", genplugin.PackageOfTypeID(id), base)
}

func schemaDraftURL(draft string) string {
	switch draft {
	case "2019-09":
		return "https://json-schema.org/draft/2019-09/schema"
	case "07", "draft-07":
		return "http://json-schema.org/draft-07/schema#"
	default:
		return "https://json-schema.org/draft/2020-12/schema"
	}
}

func (e *schemaEnc) schemaOf(t semantic.Type, asDef bool) map[string]any {
	if t.ID != "" && !asDef {
		if name, ok := e.defIDs[t.ID]; ok {
			return map[string]any{"$ref": "#/$defs/" + name}
		}
	}
	if t.ID != "" && e.emitting[t.ID] && !asDef {
		if name, ok := e.defIDs[t.ID]; ok {
			return map[string]any{"$ref": "#/$defs/" + name}
		}
	}

	resolved := genplugin.FollowAlias(e.types, t)
	chain := genplugin.ConstraintChain(e.types, t)
	schema, ok := e.baseKind(resolved)
	if !ok {
		e.warn(fmt.Sprintf("type %q kind %q is not JSON Schema representable", t.ID, resolved.Kind))
		return map[string]any{}
	}
	e.applyConstraints(schema, resolved.Kind, chain)
	return schema
}

func (e *schemaEnc) schemaRef(id string) map[string]any {
	if id == "" {
		return map[string]any{}
	}
	if name, ok := e.defIDs[id]; ok {
		return map[string]any{"$ref": "#/$defs/" + name}
	}
	return e.schemaOf(genplugin.Lookup(e.types, id), false)
}

func (e *schemaEnc) baseKind(t semantic.Type) (map[string]any, bool) {
	switch t.Kind {
	case "string":
		return map[string]any{"type": "string"}, true
	case "int":
		return map[string]any{"type": "integer"}, true
	case "float":
		return map[string]any{"type": "number"}, true
	case "bool":
		return map[string]any{"type": "boolean"}, true
	case "bytes":
		return map[string]any{"type": "string", "contentEncoding": "base64"}, true
	case "void":
		return map[string]any{"type": "null"}, true
	case "error":
		return map[string]any{"type": "object"}, true
	case "array":
		s := map[string]any{"type": "array"}
		if t.Element != "" {
			s["items"] = e.schemaRef(t.Element)
		}
		if t.Length != nil {
			s["minItems"] = *t.Length
			s["maxItems"] = *t.Length
		}
		return s, true
	case "map":
		s := map[string]any{"type": "object"}
		if t.Value != "" {
			s["additionalProperties"] = e.schemaRef(t.Value)
		} else {
			s["additionalProperties"] = true
		}
		return s, true
	case "pointer":
		inner := e.schemaRef(t.Inner)
		return map[string]any{"anyOf": []any{inner, map[string]any{"type": "null"}}}, true
	case "shape":
		return e.shapeSchema(t), true
	case "union":
		return map[string]any{"anyOf": e.memberSchemas(t.Members)}, true
	case "intersection":
		return map[string]any{"allOf": e.memberSchemas(t.Members)}, true
	case "tuple":
		return map[string]any{
			"type":            "array",
			"prefixItems":     e.memberSchemas(t.Members),
			"minItems":        len(t.Members),
			"maxItems":        len(t.Members),
			"additionalItems": false,
		}, true
	case "result":
		return map[string]any{
			"anyOf": []any{
				map[string]any{
					"type":       "object",
					"properties": map[string]any{"ok": map[string]any{"const": true}, "value": e.schemaRef(t.Success)},
					"required":   []string{"ok", "value"},
				},
				map[string]any{
					"type":       "object",
					"properties": map[string]any{"ok": map[string]any{"const": false}, "error": e.schemaRef(t.Failure)},
					"required":   []string{"ok", "error"},
				},
			},
		}, true
	case "nominalError":
		s := map[string]any{"type": "object"}
		if t.Payload != "" {
			payload := e.schemaRef(t.Payload)
			if props, ok := payload["properties"]; ok {
				s["properties"] = props
			}
			if req, ok := payload["required"]; ok {
				s["required"] = req
			}
		}
		return s, true
	case "channel":
		e.warn(fmt.Sprintf("type %q is a channel; not representable as JSON Schema", t.ID))
		return map[string]any{"not": true}, true
	case "goType", "unknown", "func":
		e.warn(fmt.Sprintf("type %q kind %q is not portable JSON Schema", t.ID, t.Kind))
		return map[string]any{}, true
	case "alias":
		if t.Underlying != "" {
			return e.schemaRef(t.Underlying), true
		}
		return map[string]any{}, true
	default:
		return nil, false
	}
}

func (e *schemaEnc) memberSchemas(ids []string) []any {
	out := make([]any, 0, len(ids))
	for _, id := range ids {
		out = append(out, e.schemaRef(id))
	}
	return out
}

func (e *schemaEnc) shapeSchema(t semantic.Type) map[string]any {
	props := map[string]any{}
	var required []string
	for _, f := range t.Fields {
		if f.Method {
			continue
		}
		props[f.Name] = e.schemaRef(f.Type)
		if !f.Optional {
			required = append(required, f.Name)
		}
	}
	sort.Strings(required)
	s := map[string]any{"type": "object", "additionalProperties": false, "properties": props}
	if len(required) > 0 {
		s["required"] = required
	}
	return s
}

func (e *schemaEnc) warn(msg string) {
	e.warnings = append(e.warnings, msg)
}

func (e *schemaEnc) applyConstraints(schema map[string]any, kind string, chain []semantic.Constraint) {
	var extra []any
	for _, c := range chain {
		if c.Name == "Router" || c.Name == "Valid" {
			continue
		}
		if c.Origin == "typeGuard" {
			e.warn(fmt.Sprintf("constraint %q is a type guard predicate; not emitted as JSON Schema", c.Name))
			continue
		}
		if c.Origin != "builtin" {
			continue
		}
		switch c.Name {
		case "Min":
			applyBound(schema, kind, c, true)
		case "Max":
			applyBound(schema, kind, c, false)
		case "LessThan":
			if n, ok := numericArg(c.Args); ok {
				schema["exclusiveMaximum"] = n
			}
		case "GreaterThan":
			if n, ok := numericArg(c.Args); ok {
				schema["exclusiveMinimum"] = n
			}
		case "HasPrefix":
			if kind == "string" {
				if prefix, ok := stringArg(c.Args); ok {
					extra = append(extra, map[string]any{"pattern": "^" + quoteMeta(prefix)})
				}
			}
		case "Contains":
			if kind == "string" {
				if sub, ok := stringArg(c.Args); ok {
					extra = append(extra, map[string]any{"pattern": ".*" + quoteMeta(sub) + ".*"})
				}
			}
		case "NotEmpty":
			switch kind {
			case "string":
				schema["minLength"] = 1
			case "array":
				schema["minItems"] = 1
			}
		case "True":
			schema["const"] = true
		case "False":
			schema["const"] = false
		case "Nil":
			schema["type"] = "null"
		case "Present":
			schema["not"] = map[string]any{"type": "null"}
		case astValue:
			if len(c.Args) >= 1 {
				schema["const"] = c.Args[0]
			}
		}
	}
	mergePatterns(schema, extra)
}

const astValue = "Value"

func applyBound(schema map[string]any, kind string, c semantic.Constraint, min bool) {
	n, ok := numericArg(c.Args)
	if !ok {
		return
	}
	target := c.Applies
	if target == "" {
		switch kind {
		case "string":
			target = "length"
		case "array":
			target = "items"
		case "int", "float":
			target = "value"
		}
	}
	switch target {
	case "length":
		if min {
			schema["minLength"] = n
		} else {
			schema["maxLength"] = n
		}
	case "items":
		if min {
			schema["minItems"] = n
		} else {
			schema["maxItems"] = n
		}
	case "value":
		if min {
			schema["minimum"] = n
		} else {
			schema["maximum"] = n
		}
	}
}

func mergePatterns(schema map[string]any, extra []any) {
	if len(extra) == 0 {
		return
	}
	if len(extra) == 1 {
		if p, ok := extra[0].(map[string]any)["pattern"].(string); ok {
			schema["pattern"] = p
		}
		return
	}
	if existing, ok := schema["allOf"].([]any); ok {
		schema["allOf"] = append(existing, extra...)
		return
	}
	schema["allOf"] = extra
}

func numericArg(args []any) (float64, bool) {
	if len(args) == 0 {
		return 0, false
	}
	switch v := args[0].(type) {
	case float64:
		return v, true
	case int:
		return float64(v), true
	case int64:
		return float64(v), true
	case json.Number:
		f, err := v.Float64()
		return f, err == nil
	default:
		return 0, false
	}
}

func stringArg(args []any) (string, bool) {
	if len(args) == 0 {
		return "", false
	}
	s, ok := args[0].(string)
	return s, ok
}

func quoteMeta(s string) string {
	// regexp.QuoteMeta without importing regexp in this file's hot path of schema keys
	b := make([]byte, 0, len(s)*2)
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '.', '+', '*', '?', '(', ')', '|', '[', ']', '{', '}', '\\', '^', '$':
			b = append(b, '\\', c)
		default:
			b = append(b, c)
		}
	}
	return string(b)
}
