package genplugin

import (
	"fmt"
	"strings"
)

// TSGeneratedHeader is prepended to every TypeScript file emitted by official plugins.
const TSGeneratedHeader = "// Code generated by Forst semantic plugins. DO NOT EDIT.\n"

// TSFile returns a generated TypeScript output file with the standard header.
func TSFile(path, body string) string {
	return TSGeneratedHeader + body
}

// TSInvokePositional emits a positional invoke call expression for @forst/gen clients.
func TSInvokePositional(clientImport, pkg, fn string, argsExpr string) string {
	if clientImport == "" {
		clientImport = "@forst/gen"
	}
	return fmt.Sprintf(`await %s.invoke("%s", "%s", [%s])`, clientImport, pkg, fn, argsExpr)
}

// TSIdentifier sanitizes a snapshot name for TypeScript identifiers.
func TSIdentifier(name string) string {
	if name == "" {
		return "_"
	}
	var b strings.Builder
	for i, r := range name {
		if i == 0 && r >= '0' && r <= '9' {
			b.WriteByte('_')
		}
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_' || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}
