package main

import (
	"fmt"
	transformerts "forst/internal/transformer/ts"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sirupsen/logrus"
)

// writeSSRModule writes the configured SSR invoke surface relative to boundaryRoot.
// Imports use paths into outDir/dist (inlined transport), never @forst/client.
func writeSSRModule(
	boundaryRoot, ssrRelPath, outDir string,
	outputs []*transformerts.TypeScriptOutput,
	invokePort string,
	log *logrus.Logger,
	stats *generateWriteStats,
) error {
	modulePath := filepath.Join(boundaryRoot, filepath.Clean(ssrRelPath))
	if err := generateIO.MkdirAll(filepath.Dir(modulePath), 0755); err != nil {
		return fmt.Errorf("failed to create SSR module directory: %w", err)
	}

	distDir := filepath.Join(outDir, "dist")
	moduleDir := filepath.Dir(modulePath)
	transportImport, err := relativeJSImport(moduleDir, filepath.Join(distDir, "transport", "runtime"))
	if err != nil {
		return fmt.Errorf("SSR transport import path: %w", err)
	}
	typesImport, err := relativeJSImport(moduleDir, filepath.Join(distDir, "types"))
	if err != nil {
		return fmt.Errorf("SSR types import path: %w", err)
	}

	sorted := append([]*transformerts.TypeScriptOutput(nil), outputs...)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].PackageName < sorted[j].PackageName
	})

	var body strings.Builder
	body.WriteString("// Auto-generated Forst SSR invoke surface\n")
	body.WriteString("// Generated by forst generate — import from the configured generate.ssrModule path\n")
	body.WriteString(strings.TrimSuffix(transformerts.GeneratedHeaderComment(invokePort), "\n"))
	body.WriteString("\n\n")
	fmt.Fprintf(&body, "import { getDefaultInvokeClient } from '%s';\n", transportImport)
	typeNames := transformerts.CollectInvokeTypeNames(sorted)
	if len(typeNames) > 0 {
		fmt.Fprintf(&body, "import type { %s } from '%s';\n", strings.Join(typeNames, ", "), typesImport)
	}
	body.WriteString("\n")
	for _, out := range sorted {
		if len(out.Functions) == 0 {
			continue
		}
		for _, line := range transformerts.DirectInvokeExportLines(out.PackageName, out.Functions) {
			body.WriteString(line)
			body.WriteString("\n\n")
		}
	}

	if err := writeGeneratedFile(modulePath, []byte(body.String()), stats); err != nil {
		return fmt.Errorf("failed to write SSR invoke module: %w", err)
	}
	log.WithFields(logrus.Fields{
		"ssrModule": ssrRelPath,
		"path":      modulePath,
	}).Debug("Generated SSR invoke module")
	return nil
}

// relativeJSImport returns a relative ESM specifier from fromDir to toPathWithoutExt (.js suffix).
func relativeJSImport(fromDir, toPathWithoutExt string) (string, error) {
	rel, err := filepath.Rel(fromDir, toPathWithoutExt)
	if err != nil {
		return "", err
	}
	rel = filepath.ToSlash(rel)
	if !strings.HasPrefix(rel, ".") {
		rel = "./" + rel
	}
	return rel + ".js", nil
}
