package transformergo

import (
	"fmt"
	"strings"

	"forst/internal/ast"
	"forst/internal/discovery"
	"forst/internal/invokecodec"
)

const (
	forstInvokeServerFileStem   = "forst_invoke_server.gen"
	forstInvokeRegistryVar      = "forstInvokeRegistry"
	forstInvokeRegistryInitDone = "forstInvokeRegistryInit"
	invokeserverImportPath      = "forst/internal/invokeserver"
	invokedispatchImportPath    = "forst/internal/invokedispatch"
)

// ForstInvokeServerFileName is the base name (without .go) for the generated invoke server companion.
func ForstInvokeServerFileName() string {
	return forstInvokeServerFileStem
}

// EmitNeedsInvokeServer reports whether generated Go should embed the invoke HTTP server.
func EmitNeedsInvokeServer(enabled bool) bool {
	return enabled
}

// InvokeServerSource returns generated Go source for the invoke server companion file.
func (t *Transformer) InvokeServerSource(embedInvoke bool, entryNodes []ast.Node) (string, error) {
	if t == nil || t.TypeChecker == nil || !EmitNeedsInvokeServer(embedInvoke) {
		return "", nil
	}
	functions := discovery.CollectInvokeFunctionsFromNodes(entryNodes, t.TypeChecker)
	if len(functions) == 0 {
		return "", nil
	}
	pkgName := t.Output.PackageName()
	if pkgName == "" {
		pkgName = "main"
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by Forst; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	b.WriteString(`import (
	"encoding/json"
	"fmt"

	"forst/internal/invokedispatch"
	"forst/internal/invokeserver"
)

`)
	fmt.Fprintf(&b, "var %s bool\n\n", forstInvokeRegistryInitDone)

	for _, fn := range functions {
		b.WriteString(emitInvokeHandler(fn))
		b.WriteString("\n")
	}

	b.WriteString(`func init() {
	if forstInvokeRegistryInit {
		return
	}
	forstInvokeRegistryInit = true
	reg := invokeserver.GlobalRegistry()
`)
	for _, fn := range functions {
		handlerName := invokeHandlerName(fn)
		fmt.Fprintf(&b, "\treg.RegisterMeta(%s, %s)\n", invokeFunctionMetaLiteral(fn), handlerName)
	}
	b.WriteString("\tinvokeserver.MustStartEmbedded()\n")
	b.WriteString("}\n\n")

	b.WriteString(`// ForstInvokeWaitForShutdown blocks until SIGINT/SIGTERM. Use in long-lived host-mode binaries.
func ForstInvokeWaitForShutdown() {
	invokeserver.WaitForShutdown()
}
`)
	return b.String(), nil
}

func invokeHandlerName(fn discovery.FunctionInfo) string {
	return fmt.Sprintf("forst_invoke_%s_%s", sanitizeInvokeIdent(fn.Package), sanitizeInvokeIdent(fn.Name))
}

func sanitizeInvokeIdent(s string) string {
	out := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			return r
		}
		return '_'
	}, s)
	return strings.Trim(out, "_")
}

func emitInvokeHandler(fn discovery.FunctionInfo) string {
	handlerName := invokeHandlerName(fn)
	paramNames := make([]string, len(fn.Parameters))
	for i, p := range fn.Parameters {
		paramNames[i] = p.Name
	}
	decode := invokecodec.DecodeArgsFromJSON("forstInvokeArgs", fn.Parameters)
	call := invokecodec.CallExpression(fn, paramNames)

	var b strings.Builder
	fmt.Fprintf(&b, "func %s(args json.RawMessage) (any, error) {\n", handlerName)
	if decode != "" {
		b.WriteString(decode)
	}
	b.WriteString("\t")
	b.WriteString(call)
	b.WriteString("\n}\n")
	return b.String()
}

func invokeFunctionMetaLiteral(fn discovery.FunctionInfo) string {
	return fmt.Sprintf("invokedispatch.FunctionMeta{Package:%q,Name:%q,SupportsStreaming:%v,Runnable:%v}",
		fn.Package, fn.Name, fn.SupportsStreaming, fn.Runnable)
}
