package transformergo

import (
	"fmt"
	"sort"
	"strings"

	"forst/internal/ast"
	"forst/internal/discovery"
	"forst/internal/invokecodec"
	"forst/internal/modulecheck"
)

const (
	forstInvokeServerFileStem   = "forst_invoke_server.gen"
	forstInvokeRegistryInitDone = "forstInvokeRegistryInit"
)

// ForstInvokeServerFileName is the base name (without .go) for the generated invoke server companion.
func ForstInvokeServerFileName() string {
	return forstInvokeServerFileStem
}

// EmitNeedsInvokeServer reports whether generated Go should embed the invoke HTTP server.
func EmitNeedsInvokeServer(enabled bool) bool {
	return enabled
}

// InvokeServerSource returns generated Go source for the invoke server companion file.
func (t *Transformer) InvokeServerSource(embedInvoke bool, entryNodes []ast.Node) (string, error) {
	if t == nil || t.TypeChecker == nil || !EmitNeedsInvokeServer(embedInvoke) {
		return "", nil
	}
	functions := discovery.CollectInvokeFunctionsFromNodes(entryNodes, t.TypeChecker)
	return t.InvokeServerSourceFromFunctions(embedInvoke, functions)
}

// InvokeServerSourceFromFunctions generates companion source for the given runnable exports.
func (t *Transformer) InvokeServerSourceFromFunctions(embedInvoke bool, functions []discovery.FunctionInfo) (string, error) {
	if t == nil || !EmitNeedsInvokeServer(embedInvoke) || len(functions) == 0 {
		return "", nil
	}
	localPkg := t.Output.PackageName()
	if localPkg == "" {
		localPkg = "main"
	}

	imports := collectInvokeImports(t, functions, localPkg)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by Forst; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", localPkg)
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n\n")
	b.WriteString("\t\"forst/invokeembed\"\n")
	for _, imp := range imports {
		fmt.Fprintf(&b, "\t%q\n", imp)
	}
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "var %s bool\n\n", forstInvokeRegistryInitDone)

	for _, fn := range functions {
		b.WriteString(emitInvokeHandlerQualified(fn, localPkg))
		b.WriteString("\n")
	}

	b.WriteString(`func init() {
	if forstInvokeRegistryInit {
		return
	}
	forstInvokeRegistryInit = true
	reg := invokeembed.GlobalRegistry()
`)
	for _, fn := range functions {
		handlerName := invokeHandlerName(fn)
		fmt.Fprintf(&b, "\treg.RegisterMeta(%s, %s)\n", invokeFunctionMetaLiteral(fn), handlerName)
	}
	b.WriteString("\tinvokeembed.MustStartEmbedded()\n")
	b.WriteString("}\n\n")

	b.WriteString(`// ForstInvokeWaitForShutdown blocks until SIGINT/SIGTERM. Use in long-lived host-mode binaries.
func ForstInvokeWaitForShutdown() {
	invokeembed.WaitForShutdown()
}
`)
	return b.String(), nil
}

func collectInvokeImports(t *Transformer, functions []discovery.FunctionInfo, localPkg string) []string {
	if t == nil || t.moduleResult == nil {
		return nil
	}
	seen := make(map[string]struct{})
	var out []string
	for _, fn := range functions {
		if fn.Package == localPkg || fn.Package == "" {
			continue
		}
		imp := t.invokeImportPath(fn.Package)
		if imp == "" {
			continue
		}
		if _, ok := seen[imp]; ok {
			continue
		}
		seen[imp] = struct{}{}
		out = append(out, imp)
	}
	sort.Strings(out)
	return out
}

func emitInvokeHandlerQualified(fn discovery.FunctionInfo, localPkg string) string {
	handlerName := invokeHandlerName(fn)
	paramNames := make([]string, len(fn.Parameters))
	for i, p := range fn.Parameters {
		paramNames[i] = p.Name
	}
	decode := invokecodec.DecodeArgsFromJSONQualified("forstInvokeArgs", fn.Parameters, fn, localPkg)
	call := invokecodec.CallExpressionQualified(fn, paramNames, localPkg)

	var b strings.Builder
	fmt.Fprintf(&b, "func %s(args json.RawMessage) (any, error) {\n", handlerName)
	if decode != "" {
		b.WriteString(decode)
	}
	b.WriteString("\t")
	b.WriteString(call)
	b.WriteString("\n}\n")
	return b.String()
}

func invokeHandlerName(fn discovery.FunctionInfo) string {
	return fmt.Sprintf("forst_invoke_%s_%s", sanitizeInvokeIdent(fn.Package), sanitizeInvokeIdent(fn.Name))
}

func sanitizeInvokeIdent(s string) string {
	out := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			return r
		}
		return '_'
	}, s)
	return strings.Trim(out, "_")
}

func emitInvokeHandler(fn discovery.FunctionInfo) string {
	handlerName := invokeHandlerName(fn)
	paramNames := make([]string, len(fn.Parameters))
	for i, p := range fn.Parameters {
		paramNames[i] = p.Name
	}
	decode := invokecodec.DecodeArgsFromJSON("forstInvokeArgs", fn.Parameters)
	call := invokecodec.CallExpression(fn, paramNames)

	var b strings.Builder
	fmt.Fprintf(&b, "func %s(args json.RawMessage) (any, error) {\n", handlerName)
	if decode != "" {
		b.WriteString(decode)
	}
	b.WriteString("\t")
	b.WriteString(call)
	b.WriteString("\n}\n")
	return b.String()
}

func (t *Transformer) invokeImportPath(forstPkg string) string {
	if t == nil || forstPkg == "" {
		return ""
	}
	if t.SandboxModulePath != "" {
		return t.SandboxModulePath + "/" + forstPkg
	}
	if t.moduleResult == nil {
		return ""
	}
	return canonicalModuleImportPath(t.moduleResult, forstPkg)
}

func canonicalModuleImportPath(modResult *modulecheck.ModuleResult, forstPkg string) string {
	if modResult == nil {
		return ""
	}
	var candidates []string
	for imp, pkg := range modResult.ImportPathToForstPkg() {
		if pkg == forstPkg {
			candidates = append(candidates, imp)
		}
	}
	if len(candidates) == 0 {
		return ""
	}
	best := candidates[0]
	for _, c := range candidates[1:] {
		if len(c) > len(best) {
			best = c
		}
	}
	return best
}

func invokeFunctionMetaLiteral(fn discovery.FunctionInfo) string {
	return fmt.Sprintf("invokeembed.FunctionMeta{Package:%q,Name:%q,SupportsStreaming:%v,Runnable:%v}",
		fn.Package, fn.Name, fn.SupportsStreaming, fn.Runnable)
}
