// Auto-generated Forst Client
// Generated by Forst TypeScript Transformer

import { ForstClient as SidecarClient } from "@forst/sidecar";
import { example } from "../generated/example.client";

export interface ForstClientConfig {
  baseUrl?: string;
  timeout?: number;
  retries?: number;
}

export class ForstClient {
  private client: SidecarClient;
  public example: ReturnType<typeof example>;

  constructor(config?: ForstClientConfig) {
    const defaultConfig = {
      baseUrl: process.env.FORST_BASE_URL || "http://localhost:8080",
      timeout: 30000,
      retries: 3,
      ...config,
    };

    this.client = new SidecarClient(defaultConfig);
    this.example = example(this.client);
  }
}

// Export individual packages
export { example };

// Export types
export * from "./types";

// Export default
export default ForstClient;
