// Auto-generated types for Forst client
// Generated by Forst TypeScript Transformer

// Type definitions
export interface User {
  name: any;
  age: any;
  email: any;
  id: any;
}

export interface CreateUserRequest {
  name: any;
  age: any;
  email: any;
}

export interface CreateUserResponse {
  user: User;
  created_at: any;
}

export interface T_TndA4HRxw7P {
  id: any;
  name: any;
  age: any;
  email: any;
}

export interface T_N142uWz7bTR {
  id: any;
  name: any;
  age: any;
  email: any;
}

export interface T_JrLVDGdHxf2 {
  id: any;
  name: any;
  age: any;
  email: any;
}

export interface T_NGUd7jXQkPf {
  created_at: any;
  user: T_TndA4HRxw7P;
}

// Function signatures
export function CreateUser(input: CreateUserRequest): Promise<any>;

export function GetUserById(id: any): Promise<any>;

export function UpdateUserAge(id: any, newAge: any): Promise<any>;
