name: Release Created

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Build and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
        run: |
          # Extract version info from tag
          VERSION=${RELEASE_VERSION#v}
          COMMIT=$(git rev-parse HEAD)
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Build binaries for multiple platforms with version info
          task build:release VERSION=$VERSION COMMIT=$COMMIT DATE=$DATE

          # Upload assets to the release
          gh release upload $RELEASE_VERSION \
            ./dist/*.tar.gz \
            ./dist/*.zip \
            --clobber
